// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
    business_id, name, address, phone, email, metadata, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, business_id, name, address, phone, email, metadata, is_active, created_at, updated_at
`

type CreateBranchParams struct {
	BusinessID int32                 `json:"business_id"`
	Name       string                `json:"name"`
	Address    sql.NullString        `json:"address"`
	Phone      sql.NullString        `json:"phone"`
	Email      sql.NullString        `json:"email"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	IsActive   bool                  `json:"is_active"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, createBranch,
		arg.BusinessID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Metadata,
		arg.IsActive,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (
    tenants_id, name, motto, email, website, tax_id, vat_number,
    country, logo_url, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10
) RETURNING id, tenants_id, name, motto, email, website, tax_id, vat_number, country, logo_url, is_active, metadata, created_at, updated_at
`

type CreateBusinessParams struct {
	TenantsID int32                 `json:"tenants_id"`
	Name      string                `json:"name"`
	Motto     sql.NullString        `json:"motto"`
	Email     sql.NullString        `json:"email"`
	Website   sql.NullString        `json:"website"`
	TaxID     sql.NullString        `json:"tax_id"`
	VatNumber sql.NullString        `json:"vat_number"`
	Country   string                `json:"country"`
	LogoUrl   sql.NullString        `json:"logo_url"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, createBusiness,
		arg.TenantsID,
		arg.Name,
		arg.Motto,
		arg.Email,
		arg.Website,
		arg.TaxID,
		arg.VatNumber,
		arg.Country,
		arg.LogoUrl,
		arg.Metadata,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.TenantsID,
		&i.Name,
		&i.Motto,
		&i.Email,
		&i.Website,
		&i.TaxID,
		&i.VatNumber,
		&i.Country,
		&i.LogoUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBranch = `-- name: DeleteBranch :one
DELETE FROM branches
WHERE id = $1
RETURNING id, business_id, name, address, phone, email, metadata, is_active, created_at, updated_at
`

func (q *Queries) DeleteBranch(ctx context.Context, id int32) (Branch, error) {
	row := q.db.QueryRowContext(ctx, deleteBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBusiness = `-- name: DeleteBusiness :one
DELETE FROM businesses
WHERE id = $1 AND tenants_id = $2
RETURNING id, tenants_id, name, motto, email, website, tax_id, vat_number, country, logo_url, is_active, metadata, created_at, updated_at
`

type DeleteBusinessParams struct {
	ID        int32 `json:"id"`
	TenantsID int32 `json:"tenants_id"`
}

func (q *Queries) DeleteBusiness(ctx context.Context, arg DeleteBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, deleteBusiness, arg.ID, arg.TenantsID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.TenantsID,
		&i.Name,
		&i.Motto,
		&i.Email,
		&i.Website,
		&i.TaxID,
		&i.VatNumber,
		&i.Country,
		&i.LogoUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTax = `-- name: DeleteTax :exec
DELETE FROM taxes
WHERE id = $1
`

func (q *Queries) DeleteTax(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTax, id)
	return err
}

const getBranch = `-- name: GetBranch :one
SELECT id, business_id, name, address, phone, email, metadata, is_active, created_at, updated_at FROM branches
WHERE id = $1 AND business_id = $2
`

type GetBranchParams struct {
	ID         int32 `json:"id"`
	BusinessID int32 `json:"business_id"`
}

func (q *Queries) GetBranch(ctx context.Context, arg GetBranchParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, getBranch, arg.ID, arg.BusinessID)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusiness = `-- name: GetBusiness :one
SELECT id, tenants_id, name, motto, email, website, tax_id, vat_number, country, logo_url, is_active, metadata, created_at, updated_at
FROM businesses
WHERE id = $1 AND tenants_id = $2
`

type GetBusinessParams struct {
	ID        int32 `json:"id"`
	TenantsID int32 `json:"tenants_id"`
}

func (q *Queries) GetBusiness(ctx context.Context, arg GetBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, getBusiness, arg.ID, arg.TenantsID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.TenantsID,
		&i.Name,
		&i.Motto,
		&i.Email,
		&i.Website,
		&i.TaxID,
		&i.VatNumber,
		&i.Country,
		&i.LogoUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxByID = `-- name: GetTaxByID :one
SELECT id, business_id, name, rate, code, is_active, note, metadata, created_at, updated_at FROM taxes
WHERE id = $1
`

func (q *Queries) GetTaxByID(ctx context.Context, id int32) (Tax, error) {
	row := q.db.QueryRowContext(ctx, getTaxByID, id)
	var i Tax
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.Code,
		&i.IsActive,
		&i.Note,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, business_id, name, address, phone, email, metadata, is_active, created_at, updated_at FROM branches
WHERE business_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBranches(ctx context.Context, businessID int32) ([]Branch, error) {
	rows, err := q.db.QueryContext(ctx, listBranches, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Metadata,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, tenants_id, name, motto, email, website, tax_id, vat_number, country, logo_url, is_active, metadata, created_at, updated_at
FROM businesses
WHERE tenants_id = $1
ORDER BY created_at
`

func (q *Queries) ListBusinesses(ctx context.Context, tenantsID int32) ([]Business, error) {
	rows, err := q.db.QueryContext(ctx, listBusinesses, tenantsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Business{}
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.TenantsID,
			&i.Name,
			&i.Motto,
			&i.Email,
			&i.Website,
			&i.TaxID,
			&i.VatNumber,
			&i.Country,
			&i.LogoUrl,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxes = `-- name: ListTaxes :many
SELECT id, business_id, name, rate, code, is_active, note, metadata, created_at, updated_at FROM taxes
WHERE business_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTaxes(ctx context.Context, businessID int32) ([]Tax, error) {
	rows, err := q.db.QueryContext(ctx, listTaxes, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tax{}
	for rows.Next() {
		var i Tax
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Rate,
			&i.Code,
			&i.IsActive,
			&i.Note,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches SET
    name = COALESCE($1, name),
    address = COALESCE($2, address),
    phone = COALESCE($3, phone),
    email = COALESCE($4, email),
    metadata = COALESCE($5, metadata),
    is_active = COALESCE($6, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, business_id, name, address, phone, email, metadata, is_active, created_at, updated_at
`

type UpdateBranchParams struct {
	Name     sql.NullString        `json:"name"`
	Address  sql.NullString        `json:"address"`
	Phone    sql.NullString        `json:"phone"`
	Email    sql.NullString        `json:"email"`
	Metadata pqtype.NullRawMessage `json:"metadata"`
	IsActive sql.NullBool          `json:"is_active"`
	ID       int32                 `json:"id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRowContext(ctx, updateBranch,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Metadata,
		arg.IsActive,
		arg.ID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses SET
    name = COALESCE($1, name),
    motto = COALESCE($2, motto),
    email = COALESCE($3, email),
    website = COALESCE($4, website),
    tax_id = COALESCE($5, tax_id),
    vat_number = COALESCE($6, vat_number),
    logo_url = COALESCE($7, logo_url),
    country = COALESCE($8, country),
    metadata = COALESCE($9, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $10 AND tenants_id = $11
RETURNING id, tenants_id, name, motto, email, website, tax_id, vat_number, country, logo_url, is_active, metadata, created_at, updated_at
`

type UpdateBusinessParams struct {
	Name      sql.NullString        `json:"name"`
	Motto     sql.NullString        `json:"motto"`
	Email     sql.NullString        `json:"email"`
	Website   sql.NullString        `json:"website"`
	TaxID     sql.NullString        `json:"tax_id"`
	VatNumber sql.NullString        `json:"vat_number"`
	LogoUrl   sql.NullString        `json:"logo_url"`
	Country   sql.NullString        `json:"country"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	ID        int32                 `json:"id"`
	TenantsID int32                 `json:"tenants_id"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, updateBusiness,
		arg.Name,
		arg.Motto,
		arg.Email,
		arg.Website,
		arg.TaxID,
		arg.VatNumber,
		arg.LogoUrl,
		arg.Country,
		arg.Metadata,
		arg.ID,
		arg.TenantsID,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.TenantsID,
		&i.Name,
		&i.Motto,
		&i.Email,
		&i.Website,
		&i.TaxID,
		&i.VatNumber,
		&i.Country,
		&i.LogoUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTax = `-- name: UpdateTax :one
UPDATE taxes
SET
    name = COALESCE($1, name),
    rate = COALESCE($2, rate),
    code = COALESCE($3, code),
    is_active = COALESCE($4, is_active),
    note = COALESCE($5, note),
    metadata = COALESCE($6, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7 AND business_id = $8
RETURNING id, business_id, name, rate, code, is_active, note, metadata, created_at, updated_at
`

type UpdateTaxParams struct {
	Name       sql.NullString        `json:"name"`
	Rate       sql.NullString        `json:"rate"`
	Code       sql.NullString        `json:"code"`
	IsActive   sql.NullBool          `json:"is_active"`
	Note       sql.NullString        `json:"note"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	ID         int32                 `json:"id"`
	BusinessID int32                 `json:"business_id"`
}

func (q *Queries) UpdateTax(ctx context.Context, arg UpdateTaxParams) (Tax, error) {
	row := q.db.QueryRowContext(ctx, updateTax,
		arg.Name,
		arg.Rate,
		arg.Code,
		arg.IsActive,
		arg.Note,
		arg.Metadata,
		arg.ID,
		arg.BusinessID,
	)
	var i Tax
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.Code,
		&i.IsActive,
		&i.Note,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
