// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (name, description, logo, business_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, business_id, description, logo, is_active, metadata, created_at, updated_at
`

type CreateBrandParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Logo        sql.NullString `json:"logo"`
	BusinessID  int32          `json:"business_id"`
}

// Brand
func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRowContext(ctx, createBrand,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.BusinessID,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.Description,
		&i.Logo,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, parent_id, description, business_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, business_id, parent_id, description, is_active, metadata, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string         `json:"name"`
	ParentID    sql.NullInt32  `json:"parent_id"`
	Description sql.NullString `json:"description"`
	BusinessID  int32          `json:"business_id"`
}

// Category
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.Name,
		arg.ParentID,
		arg.Description,
		arg.BusinessID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createColor = `-- name: CreateColor :one
INSERT INTO colors (name)
VALUES ($1)
RETURNING id, business_id, name, metadata, created_at, updated_at
`

// Color
func (q *Queries) CreateColor(ctx context.Context, name string) (Color, error) {
	row := q.db.QueryRowContext(ctx, createColor, name)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (brand_id, category_id, name, description, item_type, business_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, brand_id, category_id, name, description, item_type, is_active, metadata, created_at, updated_at
`

type CreateItemParams struct {
	BrandID     sql.NullInt32  `json:"brand_id"`
	CategoryID  int32          `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ItemType    string         `json:"item_type"`
	BusinessID  int32          `json:"business_id"`
}

// Item
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.ItemType,
		arg.BusinessID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItemImage = `-- name: CreateItemImage :one
INSERT INTO item_images (item_id, variation_id, url, is_primary)
VALUES ($1, $2, $3, $4)
RETURNING id, item_id, variation_id, url, is_primary, metadata, created_at
`

type CreateItemImageParams struct {
	ItemID      sql.NullInt32 `json:"item_id"`
	VariationID sql.NullInt32 `json:"variation_id"`
	Url         string        `json:"url"`
	IsPrimary   sql.NullBool  `json:"is_primary"`
}

// Image
func (q *Queries) CreateItemImage(ctx context.Context, arg CreateItemImageParams) (ItemImage, error) {
	row := q.db.QueryRowContext(ctx, createItemImage,
		arg.ItemID,
		arg.VariationID,
		arg.Url,
		arg.IsPrimary,
	)
	var i ItemImage
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.VariationID,
		&i.Url,
		&i.IsPrimary,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (name, short_code)
VALUES ($1, $2)
RETURNING id, business_id, name, short_code, metadata, is_active, created_at, updated_at
`

type CreateUnitParams struct {
	Name      string         `json:"name"`
	ShortCode sql.NullString `json:"short_code"`
}

// Units
func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit, arg.Name, arg.ShortCode)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.ShortCode,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariation = `-- name: CreateVariation :one
INSERT INTO variations (
item_id, sku, name, unit_id, size, color_id, barcode,cost_price, base_price, reorder_level, metadata, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, item_id, sku, name, unit_id, size, color_id, barcode, cost_price, base_price, reorder_level, is_active, metadata, created_at, updated_at
`

type CreateVariationParams struct {
	ItemID       int32                 `json:"item_id"`
	Sku          string                `json:"sku"`
	Name         string                `json:"name"`
	UnitID       int32                 `json:"unit_id"`
	Size         sql.NullString        `json:"size"`
	ColorID      sql.NullInt32         `json:"color_id"`
	Barcode      sql.NullString        `json:"barcode"`
	CostPrice    sql.NullString        `json:"cost_price"`
	BasePrice    string                `json:"base_price"`
	ReorderLevel sql.NullInt32         `json:"reorder_level"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	IsActive     sql.NullBool          `json:"is_active"`
}

// Variation
func (q *Queries) CreateVariation(ctx context.Context, arg CreateVariationParams) (Variation, error) {
	row := q.db.QueryRowContext(ctx, createVariation,
		arg.ItemID,
		arg.Sku,
		arg.Name,
		arg.UnitID,
		arg.Size,
		arg.ColorID,
		arg.Barcode,
		arg.CostPrice,
		arg.BasePrice,
		arg.ReorderLevel,
		arg.Metadata,
		arg.IsActive,
	)
	var i Variation
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Sku,
		&i.Name,
		&i.UnitID,
		&i.Size,
		&i.ColorID,
		&i.Barcode,
		&i.CostPrice,
		&i.BasePrice,
		&i.ReorderLevel,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBrand = `-- name: DeleteBrand :one
DELETE FROM brands
WHERE id = $1
RETURNING id, name, business_id, description, logo, is_active, metadata, created_at, updated_at
`

func (q *Queries) DeleteBrand(ctx context.Context, id int32) (Brand, error) {
	row := q.db.QueryRowContext(ctx, deleteBrand, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.Description,
		&i.Logo,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
RETURNING id, name, business_id, parent_id, description, is_active, metadata, created_at, updated_at
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteColor = `-- name: DeleteColor :exec
DELETE FROM colors
WHERE id = $1
RETURNING id, business_id, name, metadata, created_at, updated_at
`

func (q *Queries) DeleteColor(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteColor, id)
	return err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM inventories WHERE id = $1
`

func (q *Queries) DeleteInventory(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteInventory, id)
	return err
}

const deleteItem = `-- name: DeleteItem :one
DELETE FROM items
WHERE id = $1
RETURNING id, business_id, brand_id, category_id, name, description, item_type, is_active, metadata, created_at, updated_at
`

func (q *Queries) DeleteItem(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRowContext(ctx, deleteItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemImage = `-- name: DeleteItemImage :exec
DELETE FROM item_images WHERE id = $1
`

func (q *Queries) DeleteItemImage(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteItemImage, id)
	return err
}

const deleteUnit = `-- name: DeleteUnit :exec
DELETE FROM units
WHERE id = $1
RETURNING id, business_id, name, short_code, metadata, is_active, created_at, updated_at
`

func (q *Queries) DeleteUnit(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUnit, id)
	return err
}

const deleteVariation = `-- name: DeleteVariation :one
DELETE FROM variations
WHERE id = $1
RETURNING id, item_id, sku, name, unit_id, size, color_id, barcode, cost_price, base_price, reorder_level, is_active, metadata, created_at, updated_at
`

func (q *Queries) DeleteVariation(ctx context.Context, id int32) (Variation, error) {
	row := q.db.QueryRowContext(ctx, deleteVariation, id)
	var i Variation
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Sku,
		&i.Name,
		&i.UnitID,
		&i.Size,
		&i.ColorID,
		&i.Barcode,
		&i.CostPrice,
		&i.BasePrice,
		&i.ReorderLevel,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrand = `-- name: GetBrand :one
SELECT id, name, business_id, description, logo, is_active, metadata, created_at, updated_at FROM brands
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBrand(ctx context.Context, id int32) (Brand, error) {
	row := q.db.QueryRowContext(ctx, getBrand, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.Description,
		&i.Logo,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, business_id, parent_id, description, is_active, metadata, created_at, updated_at FROM categories
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColorByID = `-- name: GetColorByID :one
SELECT id, business_id, name, metadata, created_at, updated_at FROM colors
WHERE id = $1
`

func (q *Queries) GetColorByID(ctx context.Context, id int32) (Color, error) {
	row := q.db.QueryRowContext(ctx, getColorByID, id)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColorByName = `-- name: GetColorByName :one
SELECT id, business_id, name, metadata, created_at, updated_at FROM colors
WHERE name = $1
`

func (q *Queries) GetColorByName(ctx context.Context, name string) (Color, error) {
	row := q.db.QueryRowContext(ctx, getColorByName, name)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryByStore = `-- name: GetInventoryByStore :many
SELECT id, store_id, variation_id, quantity, metadata, last_updated FROM inventories WHERE store_id = $1
`

func (q *Queries) GetInventoryByStore(ctx context.Context, storeID int32) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, getInventoryByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.VariationID,
			&i.Quantity,
			&i.Metadata,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, store_id, variation_id, quantity, metadata, last_updated FROM inventories
WHERE store_id = $1 AND variation_id = $2
LIMIT 1
`

type GetInventoryItemParams struct {
	StoreID     int32 `json:"store_id"`
	VariationID int32 `json:"variation_id"`
}

func (q *Queries) GetInventoryItem(ctx context.Context, arg GetInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItem, arg.StoreID, arg.VariationID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.VariationID,
		&i.Quantity,
		&i.Metadata,
		&i.LastUpdated,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, business_id, brand_id, category_id, name, description, item_type, is_active, metadata, created_at, updated_at FROM items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetItem(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemImagesByItem = `-- name: GetItemImagesByItem :many
SELECT id, item_id, variation_id, url, is_primary, metadata, created_at FROM item_images WHERE item_id = $1
`

func (q *Queries) GetItemImagesByItem(ctx context.Context, itemID sql.NullInt32) ([]ItemImage, error) {
	rows, err := q.db.QueryContext(ctx, getItemImagesByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemImage{}
	for rows.Next() {
		var i ItemImage
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.VariationID,
			&i.Url,
			&i.IsPrimary,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemImagesByVariation = `-- name: GetItemImagesByVariation :many
SELECT id, item_id, variation_id, url, is_primary, metadata, created_at FROM item_images WHERE variation_id = $1
`

func (q *Queries) GetItemImagesByVariation(ctx context.Context, variationID sql.NullInt32) ([]ItemImage, error) {
	rows, err := q.db.QueryContext(ctx, getItemImagesByVariation, variationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemImage{}
	for rows.Next() {
		var i ItemImage
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.VariationID,
			&i.Url,
			&i.IsPrimary,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, business_id, name, short_code, metadata, is_active, created_at, updated_at FROM units
WHERE id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, id int32) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.ShortCode,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariation = `-- name: GetVariation :one
SELECT id, item_id, sku, name, unit_id, size, color_id, barcode, cost_price, base_price, reorder_level, is_active, metadata, created_at, updated_at FROM variations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVariation(ctx context.Context, id int32) (Variation, error) {
	row := q.db.QueryRowContext(ctx, getVariation, id)
	var i Variation
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Sku,
		&i.Name,
		&i.UnitID,
		&i.Size,
		&i.ColorID,
		&i.Barcode,
		&i.CostPrice,
		&i.BasePrice,
		&i.ReorderLevel,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrandsByBusiness = `-- name: ListBrandsByBusiness :many
SELECT id, name, business_id, description, logo, is_active, metadata, created_at, updated_at FROM brands
WHERE business_id = $1
ORDER BY name
`

func (q *Queries) ListBrandsByBusiness(ctx context.Context, businessID int32) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, listBrandsByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BusinessID,
			&i.Description,
			&i.Logo,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByBusiness = `-- name: ListCategoriesByBusiness :many
SELECT id, name, business_id, parent_id, description, is_active, metadata, created_at, updated_at FROM categories
WHERE business_id = $1
ORDER BY name
`

func (q *Queries) ListCategoriesByBusiness(ctx context.Context, businessID int32) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BusinessID,
			&i.ParentID,
			&i.Description,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColors = `-- name: ListColors :many
SELECT id, business_id, name, metadata, created_at, updated_at FROM colors
ORDER BY id
`

func (q *Queries) ListColors(ctx context.Context) ([]Color, error) {
	rows, err := q.db.QueryContext(ctx, listColors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Color{}
	for rows.Next() {
		var i Color
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByBusiness = `-- name: ListItemsByBusiness :many
SELECT id, business_id, brand_id, category_id, name, description, item_type, is_active, metadata, created_at, updated_at FROM items
WHERE business_id = $1
ORDER BY name
`

func (q *Queries) ListItemsByBusiness(ctx context.Context, businessID int32) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BrandID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.ItemType,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByCategory = `-- name: ListItemsByCategory :many
SELECT id, business_id, brand_id, category_id, name, description, item_type, is_active, metadata, created_at, updated_at FROM items
WHERE category_id = $1
ORDER BY name
`

func (q *Queries) ListItemsByCategory(ctx context.Context, categoryID int32) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.BrandID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.ItemType,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, business_id, name, short_code, metadata, is_active, created_at, updated_at FROM units
ORDER BY id
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.ShortCode,
			&i.Metadata,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariationsByItem = `-- name: ListVariationsByItem :many
SELECT id, item_id, sku, name, unit_id, size, color_id, barcode, cost_price, base_price, reorder_level, is_active, metadata, created_at, updated_at FROM variations
WHERE item_id = $1
ORDER BY name
`

func (q *Queries) ListVariationsByItem(ctx context.Context, itemID int32) ([]Variation, error) {
	rows, err := q.db.QueryContext(ctx, listVariationsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variation{}
	for rows.Next() {
		var i Variation
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Sku,
			&i.Name,
			&i.UnitID,
			&i.Size,
			&i.ColorID,
			&i.Barcode,
			&i.CostPrice,
			&i.BasePrice,
			&i.ReorderLevel,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE brands
SET name = $2,
    description = COALESCE($3, description),
    logo = COALESCE($4, logo),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, business_id, description, logo, is_active, metadata, created_at, updated_at
`

type UpdateBrandParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Logo        sql.NullString `json:"logo"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRowContext(ctx, updateBrand,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.IsActive,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.Description,
		&i.Logo,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2,
    parent_id = COALESCE($3, parent_id),
    description = COALESCE($4, description),
    is_active = COALESCE($5, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, business_id, parent_id, description, is_active, metadata, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	ParentID    sql.NullInt32  `json:"parent_id"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Description,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateColor = `-- name: UpdateColor :one
UPDATE colors
SET name = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, business_id, name, metadata, created_at, updated_at
`

type UpdateColorParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateColor(ctx context.Context, arg UpdateColorParams) (Color, error) {
	row := q.db.QueryRowContext(ctx, updateColor, arg.Name, arg.ID)
	var i Color
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInventoryQuantity = `-- name: UpdateInventoryQuantity :one
UPDATE inventories
SET quantity = $3,
    last_updated = NOW()
WHERE store_id = $1 AND variation_id = $2
RETURNING id, store_id, variation_id, quantity, metadata, last_updated
`

type UpdateInventoryQuantityParams struct {
	StoreID     int32 `json:"store_id"`
	VariationID int32 `json:"variation_id"`
	Quantity    int32 `json:"quantity"`
}

func (q *Queries) UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, updateInventoryQuantity, arg.StoreID, arg.VariationID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.VariationID,
		&i.Quantity,
		&i.Metadata,
		&i.LastUpdated,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET brand_id = COALESCE($3, brand_id),
    category_id = COALESCE($4, category_id),
    name = COALESCE($5, name),
    description = COALESCE($6, description),
    is_active = COALESCE($7, is_active),
    item_type = COALESCE($8, item_type),
    updated_at = NOW()
WHERE id = $1 AND business_id = $2
RETURNING id, business_id, brand_id, category_id, name, description, item_type, is_active, metadata, created_at, updated_at
`

type UpdateItemParams struct {
	ID          int32          `json:"id"`
	BusinessID  int32          `json:"business_id"`
	BrandID     sql.NullInt32  `json:"brand_id"`
	CategoryID  sql.NullInt32  `json:"category_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	ItemType    sql.NullString `json:"item_type"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, updateItem,
		arg.ID,
		arg.BusinessID,
		arg.BrandID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.ItemType,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.BrandID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ItemType,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units
SET name = $1,
    short_code = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, business_id, name, short_code, metadata, is_active, created_at, updated_at
`

type UpdateUnitParams struct {
	Name      string         `json:"name"`
	ShortCode sql.NullString `json:"short_code"`
	ID        int32          `json:"id"`
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, updateUnit, arg.Name, arg.ShortCode, arg.ID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.ShortCode,
		&i.Metadata,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariation = `-- name: UpdateVariation :one
UPDATE variations
SET sku = COALESCE($3, sku),
    name = COALESCE($4, name),
    unit_id = COALESCE($5, unit_id),
    size = COALESCE($6, size),
    color_id = COALESCE($7, color_id),
    barcode = COALESCE($8, barcode),
    base_price = COALESCE($9, base_price),
    reorder_level = COALESCE($10, reorder_level),
    is_active = COALESCE($11, is_active),
    updated_at = NOW()
WHERE id = $1 AND item_id = $2
RETURNING id, item_id, sku, name, unit_id, size, color_id, barcode, cost_price, base_price, reorder_level, is_active, metadata, created_at, updated_at
`

type UpdateVariationParams struct {
	ID           int32          `json:"id"`
	ItemID       int32          `json:"item_id"`
	Sku          sql.NullString `json:"sku"`
	Name         sql.NullString `json:"name"`
	UnitID       sql.NullInt32  `json:"unit_id"`
	Size         sql.NullString `json:"size"`
	ColorID      sql.NullInt32  `json:"color_id"`
	Barcode      sql.NullString `json:"barcode"`
	BasePrice    sql.NullString `json:"base_price"`
	ReorderLevel sql.NullInt32  `json:"reorder_level"`
	IsActive     sql.NullBool   `json:"is_active"`
}

func (q *Queries) UpdateVariation(ctx context.Context, arg UpdateVariationParams) (Variation, error) {
	row := q.db.QueryRowContext(ctx, updateVariation,
		arg.ID,
		arg.ItemID,
		arg.Sku,
		arg.Name,
		arg.UnitID,
		arg.Size,
		arg.ColorID,
		arg.Barcode,
		arg.BasePrice,
		arg.ReorderLevel,
		arg.IsActive,
	)
	var i Variation
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Sku,
		&i.Name,
		&i.UnitID,
		&i.Size,
		&i.ColorID,
		&i.Barcode,
		&i.CostPrice,
		&i.BasePrice,
		&i.ReorderLevel,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInventory = `-- name: UpsertInventory :one
INSERT INTO inventories (store_id, variation_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (store_id, variation_id)
DO UPDATE SET
    quantity = EXCLUDED.quantity,
    last_updated = NOW()
RETURNING id, store_id, variation_id, quantity, metadata, last_updated
`

type UpsertInventoryParams struct {
	StoreID     int32 `json:"store_id"`
	VariationID int32 `json:"variation_id"`
	Quantity    int32 `json:"quantity"`
}

// Inventory
func (q *Queries) UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, upsertInventory, arg.StoreID, arg.VariationID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.VariationID,
		&i.Quantity,
		&i.Metadata,
		&i.LastUpdated,
	)
	return i, err
}
