// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: keys.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (key_name, api_key, api_secret, tenant_id, allowed_modules, monthly_limit, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, key_name, api_key, api_secret, tenant_id, allowed_modules, monthly_limit, current_month_requests, is_active, expires_at, created_at, updated_at
`

type CreateAPIKeyParams struct {
	KeyName        string    `json:"key_name"`
	ApiKey         string    `json:"api_key"`
	ApiSecret      string    `json:"api_secret"`
	TenantID       int32     `json:"tenant_id"`
	AllowedModules []string  `json:"allowed_modules"`
	MonthlyLimit   int32     `json:"monthly_limit"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.KeyName,
		arg.ApiKey,
		arg.ApiSecret,
		arg.TenantID,
		pq.Array(arg.AllowedModules),
		arg.MonthlyLimit,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyName,
		&i.ApiKey,
		&i.ApiSecret,
		&i.TenantID,
		pq.Array(&i.AllowedModules),
		&i.MonthlyLimit,
		&i.CurrentMonthRequests,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, key_name, api_key, api_secret, tenant_id, allowed_modules, monthly_limit, current_month_requests, is_active, expires_at, created_at, updated_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id int32) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyName,
		&i.ApiKey,
		&i.ApiSecret,
		&i.TenantID,
		pq.Array(&i.AllowedModules),
		&i.MonthlyLimit,
		&i.CurrentMonthRequests,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByKey = `-- name: GetAPIKeyByKey :one
SELECT id, key_name, api_key, api_secret, tenant_id, allowed_modules, monthly_limit, current_month_requests, is_active, expires_at, created_at, updated_at FROM api_keys WHERE api_key = $1
`

func (q *Queries) GetAPIKeyByKey(ctx context.Context, apiKey string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByKey, apiKey)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyName,
		&i.ApiKey,
		&i.ApiSecret,
		&i.TenantID,
		pq.Array(&i.AllowedModules),
		&i.MonthlyLimit,
		&i.CurrentMonthRequests,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyUsageByDateRange = `-- name: GetAPIKeyUsageByDateRange :many
SELECT id, api_key_id, module_name, endpoint, request_method, request_size, response_status, ip_address, user_agent, created_at FROM api_key_usages
WHERE api_key_id = $1 AND created_at BETWEEN $2 AND $3
ORDER BY created_at DESC
`

type GetAPIKeyUsageByDateRangeParams struct {
	ApiKeyID    int32        `json:"api_key_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	CreatedAt_2 sql.NullTime `json:"created_at_2"`
}

func (q *Queries) GetAPIKeyUsageByDateRange(ctx context.Context, arg GetAPIKeyUsageByDateRangeParams) ([]ApiKeyUsage, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeyUsageByDateRange, arg.ApiKeyID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeyUsage{}
	for rows.Next() {
		var i ApiKeyUsage
		if err := rows.Scan(
			&i.ID,
			&i.ApiKeyID,
			&i.ModuleName,
			&i.Endpoint,
			&i.RequestMethod,
			&i.RequestSize,
			&i.ResponseStatus,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPIKeyUsageStats = `-- name: GetAPIKeyUsageStats :one
SELECT
    COUNT(*) as total_requests,
    COALESCE(SUM(request_size), 0) as total_bytes,
    COUNT(DISTINCT endpoint) as unique_endpoints
FROM api_key_usages
WHERE api_key_id = $1 AND created_at BETWEEN $2 AND $3
`

type GetAPIKeyUsageStatsParams struct {
	ApiKeyID    int32        `json:"api_key_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	CreatedAt_2 sql.NullTime `json:"created_at_2"`
}

type GetAPIKeyUsageStatsRow struct {
	TotalRequests   int64       `json:"total_requests"`
	TotalBytes      interface{} `json:"total_bytes"`
	UniqueEndpoints int64       `json:"unique_endpoints"`
}

func (q *Queries) GetAPIKeyUsageStats(ctx context.Context, arg GetAPIKeyUsageStatsParams) (GetAPIKeyUsageStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyUsageStats, arg.ApiKeyID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetAPIKeyUsageStatsRow
	err := row.Scan(&i.TotalRequests, &i.TotalBytes, &i.UniqueEndpoints)
	return i, err
}

const getAPIKeysByTenant = `-- name: GetAPIKeysByTenant :many
SELECT id, key_name, api_key, api_secret, tenant_id, allowed_modules, monthly_limit, current_month_requests, is_active, expires_at, created_at, updated_at FROM api_keys WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAPIKeysByTenant(ctx context.Context, tenantID int32) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyName,
			&i.ApiKey,
			&i.ApiSecret,
			&i.TenantID,
			pq.Array(&i.AllowedModules),
			&i.MonthlyLimit,
			&i.CurrentMonthRequests,
			&i.IsActive,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAPIKeyUsage = `-- name: IncrementAPIKeyUsage :exec
UPDATE api_keys
SET current_month_requests = current_month_requests + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) IncrementAPIKeyUsage(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, incrementAPIKeyUsage, id)
	return err
}

const recordAPIKeyUsage = `-- name: RecordAPIKeyUsage :one
INSERT INTO api_key_usages (api_key_id, module_name, endpoint, request_method, request_size, response_status, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, api_key_id, module_name, endpoint, request_method, request_size, response_status, ip_address, user_agent, created_at
`

type RecordAPIKeyUsageParams struct {
	ApiKeyID       int32  `json:"api_key_id"`
	ModuleName     string `json:"module_name"`
	Endpoint       string `json:"endpoint"`
	RequestMethod  string `json:"request_method"`
	RequestSize    int32  `json:"request_size"`
	ResponseStatus int32  `json:"response_status"`
	IpAddress      string `json:"ip_address"`
	UserAgent      string `json:"user_agent"`
}

func (q *Queries) RecordAPIKeyUsage(ctx context.Context, arg RecordAPIKeyUsageParams) (ApiKeyUsage, error) {
	row := q.db.QueryRowContext(ctx, recordAPIKeyUsage,
		arg.ApiKeyID,
		arg.ModuleName,
		arg.Endpoint,
		arg.RequestMethod,
		arg.RequestSize,
		arg.ResponseStatus,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ApiKeyUsage
	err := row.Scan(
		&i.ID,
		&i.ApiKeyID,
		&i.ModuleName,
		&i.Endpoint,
		&i.RequestMethod,
		&i.RequestSize,
		&i.ResponseStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const resetMonthlyUsage = `-- name: ResetMonthlyUsage :exec
UPDATE api_keys
SET current_month_requests = 0, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ResetMonthlyUsage(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, resetMonthlyUsage, id)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys
SET key_name = $2, allowed_modules = $3, monthly_limit = $4, expires_at = $5, is_active = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, key_name, api_key, api_secret, tenant_id, allowed_modules, monthly_limit, current_month_requests, is_active, expires_at, created_at, updated_at
`

type UpdateAPIKeyParams struct {
	ID             int32     `json:"id"`
	KeyName        string    `json:"key_name"`
	AllowedModules []string  `json:"allowed_modules"`
	MonthlyLimit   int32     `json:"monthly_limit"`
	ExpiresAt      time.Time `json:"expires_at"`
	IsActive       bool      `json:"is_active"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, updateAPIKey,
		arg.ID,
		arg.KeyName,
		pq.Array(arg.AllowedModules),
		arg.MonthlyLimit,
		arg.ExpiresAt,
		arg.IsActive,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyName,
		&i.ApiKey,
		&i.ApiSecret,
		&i.TenantID,
		pq.Array(&i.AllowedModules),
		&i.MonthlyLimit,
		&i.CurrentMonthRequests,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
