// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type PaymentType string

const (
	PaymentTypeCash       PaymentType = "cash"
	PaymentTypePos        PaymentType = "pos"
	PaymentTypeRoomCharge PaymentType = "room_charge"
	PaymentTypeTransfer   PaymentType = "transfer"
)

func (e *PaymentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentType(s)
	case string:
		*e = PaymentType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentType: %T", src)
	}
	return nil
}

type NullPaymentType struct {
	PaymentType PaymentType `json:"payment_type"`
	Valid       bool        `json:"valid"` // Valid is true if PaymentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentType), nil
}

type ActivityLog struct {
	ID         int32                 `json:"id"`
	UserID     int32                 `json:"user_id"`
	Action     string                `json:"action"`
	Details    string                `json:"details"`
	EntityID   int32                 `json:"entity_id"`
	EntityType string                `json:"entity_type"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  sql.NullTime          `json:"created_at"`
}

type Admin struct {
	ID                    int32          `json:"id"`
	FirstName             string         `json:"first_name"`
	LastName              string         `json:"last_name"`
	Username              string         `json:"username"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	RoleID                int32          `json:"role_id"`
	IsActive              bool           `json:"is_active"`
	EmailVerified         bool           `json:"email_verified"`
	VerificationCode      sql.NullString `json:"verification_code"`
	VerificationExpiresAt sql.NullTime   `json:"verification_expires_at"`
	ResetCode             sql.NullString `json:"reset_code"`
	ResetCodeExpiresAt    sql.NullTime   `json:"reset_code_expires_at"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
}

type ApiKey struct {
	ID                   int32        `json:"id"`
	KeyName              string       `json:"key_name"`
	ApiKey               string       `json:"api_key"`
	ApiSecret            string       `json:"api_secret"`
	UserID               int32        `json:"user_id"`
	AllowedModules       []string     `json:"allowed_modules"`
	MonthlyLimit         int32        `json:"monthly_limit"`
	CurrentMonthRequests int32        `json:"current_month_requests"`
	IsActive             bool         `json:"is_active"`
	ExpiresAt            time.Time    `json:"expires_at"`
	CreatedAt            sql.NullTime `json:"created_at"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
}

type ApiKeyUsage struct {
	ID             int32        `json:"id"`
	ApiKeyID       int32        `json:"api_key_id"`
	ModuleName     string       `json:"module_name"`
	Endpoint       string       `json:"endpoint"`
	RequestMethod  string       `json:"request_method"`
	RequestSize    int32        `json:"request_size"`
	ResponseStatus int32        `json:"response_status"`
	IpAddress      string       `json:"ip_address"`
	UserAgent      string       `json:"user_agent"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Branch struct {
	ID         int32                 `json:"id"`
	BusinessID int32                 `json:"business_id"`
	Name       string                `json:"name"`
	Address    sql.NullString        `json:"address"`
	Phone      sql.NullString        `json:"phone"`
	Email      sql.NullString        `json:"email"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	IsActive   sql.NullBool          `json:"is_active"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

type Brand struct {
	ID          int32                 `json:"id"`
	Name        string                `json:"name"`
	BusinessID  int32                 `json:"business_id"`
	Description sql.NullString        `json:"description"`
	Logo        sql.NullString        `json:"logo"`
	IsActive    sql.NullBool          `json:"is_active"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type Business struct {
	ID        int32                 `json:"id"`
	OwnerID   int32                 `json:"owner_id"`
	Name      string                `json:"name"`
	Motto     sql.NullString        `json:"motto"`
	Email     sql.NullString        `json:"email"`
	Website   sql.NullString        `json:"website"`
	TaxID     sql.NullString        `json:"tax_id"`
	VatNumber sql.NullString        `json:"vat_number"`
	Country   string                `json:"country"`
	LogoUrl   sql.NullString        `json:"logo_url"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
	UpdatedAt sql.NullTime          `json:"updated_at"`
}

type Category struct {
	ID          int32                 `json:"id"`
	Name        string                `json:"name"`
	BusinessID  int32                 `json:"business_id"`
	ParentID    sql.NullInt32         `json:"parent_id"`
	Description sql.NullString        `json:"description"`
	IsActive    sql.NullBool          `json:"is_active"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type Color struct {
	ID         int32                 `json:"id"`
	BusinessID int32                 `json:"business_id"`
	Name       string                `json:"name"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

type Inventory struct {
	ID          int32                 `json:"id"`
	StoreID     int32                 `json:"store_id"`
	VariationID int32                 `json:"variation_id"`
	Quantity    int32                 `json:"quantity"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	LastUpdated sql.NullTime          `json:"last_updated"`
}

type Item struct {
	ID          int32                 `json:"id"`
	BusinessID  int32                 `json:"business_id"`
	BrandID     sql.NullInt32         `json:"brand_id"`
	CategoryID  int32                 `json:"category_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	ItemType    string                `json:"item_type"`
	IsActive    sql.NullBool          `json:"is_active"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type ItemImage struct {
	ID          int32                 `json:"id"`
	ItemID      sql.NullInt32         `json:"item_id"`
	VariationID sql.NullInt32         `json:"variation_id"`
	Url         string                `json:"url"`
	IsPrimary   sql.NullBool          `json:"is_primary"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   sql.NullTime          `json:"created_at"`
}

type LoginHistory struct {
	ID              int32          `json:"id"`
	UsernameOrEmail string         `json:"username_or_email"`
	LoginTime       sql.NullTime   `json:"login_time"`
	IpAddress       sql.NullString `json:"ip_address"`
	UserAgent       sql.NullString `json:"user_agent"`
	Success         bool           `json:"success"`
	ErrorReason     sql.NullString `json:"error_reason"`
}

type PasswordResetToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
}

type Permission struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

type Purchase struct {
	ID                  int32          `json:"id"`
	SupplierID          int32          `json:"supplier_id"`
	BranchID            int32          `json:"branch_id"`
	InvoiceNumber       sql.NullString `json:"invoice_number"`
	PurchaseOrderNumber string         `json:"purchase_order_number"`
	TotalAmount         sql.NullString `json:"total_amount"`
	Note                sql.NullString `json:"note"`
	Status              string         `json:"status"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type PurchaseItem struct {
	ID         int32                 `json:"id"`
	ProductID  int32                 `json:"product_id"`
	PurchaseID int32                 `json:"purchase_id"`
	Quantity   int32                 `json:"quantity"`
	UnitPrice  string                `json:"unit_price"`
	TaxID      sql.NullInt32         `json:"tax_id"`
	TotalPrice string                `json:"total_price"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

type RefreshToken struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Revoked   sql.NullBool `json:"revoked"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type Store struct {
	ID           int32                 `json:"id"`
	Name         string                `json:"name"`
	Description  sql.NullString        `json:"description"`
	BranchID     int32                 `json:"branch_id"`
	Address      string                `json:"address"`
	Phone        string                `json:"phone"`
	Email        string                `json:"email"`
	IsActive     sql.NullBool          `json:"is_active"`
	StoreType    string                `json:"store_type"`
	StoreCode    string                `json:"store_code"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
	AssignedUser sql.NullInt32         `json:"assigned_user"`
	ManagerID    sql.NullInt32         `json:"manager_id"`
}

type StorePrice struct {
	ID          int32                 `json:"id"`
	StoreID     int32                 `json:"store_id"`
	VariationID int32                 `json:"variation_id"`
	Price       string                `json:"price"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

type Supplier struct {
	ID         int32                 `json:"id"`
	Name       string                `json:"name"`
	Phone      sql.NullString        `json:"phone"`
	Email      sql.NullString        `json:"email"`
	Address    sql.NullString        `json:"address"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	BusinessID int32                 `json:"business_id"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

type Tax struct {
	ID         int32                 `json:"id"`
	BusinessID int32                 `json:"business_id"`
	Name       string                `json:"name"`
	Rate       string                `json:"rate"`
	Code       string                `json:"code"`
	IsActive   bool                  `json:"is_active"`
	Note       sql.NullString        `json:"note"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

type Unit struct {
	ID         int32                 `json:"id"`
	BusinessID int32                 `json:"business_id"`
	Name       string                `json:"name"`
	ShortCode  sql.NullString        `json:"short_code"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	IsActive   sql.NullBool          `json:"is_active"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

type UnitConversion struct {
	ID         int32  `json:"id"`
	BusinessID int32  `json:"business_id"`
	FromUnitID int32  `json:"from_unit_id"`
	ToUnitID   int32  `json:"to_unit_id"`
	Factor     string `json:"factor"`
}

type User struct {
	ID           int32                 `json:"id"`
	Username     string                `json:"username"`
	FirstName    string                `json:"first_name"`
	LastName     string                `json:"last_name"`
	Email        sql.NullString        `json:"email"`
	PasswordHash string                `json:"password_hash"`
	Gender       sql.NullString        `json:"gender"`
	RoleID       sql.NullInt32         `json:"role_id"`
	IsActive     sql.NullBool          `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}

type Variation struct {
	ID           int32                 `json:"id"`
	ItemID       int32                 `json:"item_id"`
	Sku          string                `json:"sku"`
	Name         string                `json:"name"`
	UnitID       int32                 `json:"unit_id"`
	Size         sql.NullString        `json:"size"`
	ColorID      sql.NullInt32         `json:"color_id"`
	Barcode      sql.NullString        `json:"barcode"`
	CostPrice    sql.NullString        `json:"cost_price"`
	BasePrice    string                `json:"base_price"`
	ReorderLevel sql.NullInt32         `json:"reorder_level"`
	IsActive     sql.NullBool          `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}

type VariationTax struct {
	ID          int32 `json:"id"`
	VariationID int32 `json:"variation_id"`
	TaxID       int32 `json:"tax_id"`
}

type Webhook struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	Secret      string         `json:"secret"`
	Events      []string       `json:"events"`
	UserID      int32          `json:"user_id"`
	IsActive    sql.NullBool   `json:"is_active"`
	RetryCount  sql.NullInt32  `json:"retry_count"`
	MaxRetries  sql.NullInt32  `json:"max_retries"`
	TimeoutMs   sql.NullInt32  `json:"timeout_ms"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type WebhookDelivery struct {
	ID             int32           `json:"id"`
	WebhookID      int32           `json:"webhook_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	ResponseStatus sql.NullInt32   `json:"response_status"`
	ResponseBody   sql.NullString  `json:"response_body"`
	ErrorMessage   sql.NullString  `json:"error_message"`
	AttemptNumber  sql.NullInt32   `json:"attempt_number"`
	DeliveredAt    sql.NullTime    `json:"delivered_at"`
	CreatedAt      sql.NullTime    `json:"created_at"`
}

type WebhookEvent struct {
	ID          int32          `json:"id"`
	EventType   string         `json:"event_type"`
	Description sql.NullString `json:"description"`
	Module      string         `json:"module"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
