// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :one

INSERT INTO user_role_assignments (
    user_id, tenant_role_id, business_id, branch_id, assigned_by, expires_at, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, tenant_role_id, business_id, branch_id, assigned_by, assigned_at, expires_at, is_active, metadata
`

type AssignRoleToUserParams struct {
	UserID       int32                 `json:"user_id"`
	TenantRoleID int32                 `json:"tenant_role_id"`
	BusinessID   sql.NullInt32         `json:"business_id"`
	BranchID     sql.NullInt32         `json:"branch_id"`
	AssignedBy   sql.NullInt32         `json:"assigned_by"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

// ========================================
// USER ROLE ASSIGNMENTS QUERIES
// ========================================
func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (UserRoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignRoleToUser,
		arg.UserID,
		arg.TenantRoleID,
		arg.BusinessID,
		arg.BranchID,
		arg.AssignedBy,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i UserRoleAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantRoleID,
		&i.BusinessID,
		&i.BranchID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.Metadata,
	)
	return i, err
}

const checkRolePermission = `-- name: CheckRolePermission :one
SELECT COUNT(*) > 0 as has_permission
FROM tenant_role_permissions trp
WHERE trp.tenant_role_id = $1 AND trp.permission_id = $2
AND trp.scope_type = $3
AND (trp.scope_id = $4 OR ($4::integer IS NULL AND trp.scope_id IS NULL))
AND trp.is_active = true
`

type CheckRolePermissionParams struct {
	TenantRoleID int32          `json:"tenant_role_id"`
	PermissionID int32          `json:"permission_id"`
	ScopeType    sql.NullString `json:"scope_type"`
	ScopeID      sql.NullInt32  `json:"scope_id"`
}

func (q *Queries) CheckRolePermission(ctx context.Context, arg CheckRolePermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkRolePermission,
		arg.TenantRoleID,
		arg.PermissionID,
		arg.ScopeType,
		arg.ScopeID,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const checkUserPermission = `-- name: CheckUserPermission :one
WITH RECURSIVE role_hierarchy AS (
    -- Get direct role assignments for the user
    SELECT DISTINCT tr.id AS role_id, tr.parent_role_id
    FROM tenant_roles tr
    JOIN user_role_assignments ura ON tr.id = ura.tenant_role_id
    WHERE ura.user_id = $1 AND tr.tenant_id = $2
    AND ura.is_active = TRUE
    AND (ura.expires_at IS NULL OR ura.expires_at > NOW())
    AND (ura.business_id = $4 OR $4::integer IS NULL OR ura.business_id IS NULL)
    AND (ura.branch_id = $5 OR $5::integer IS NULL OR ura.branch_id IS NULL)

    UNION ALL

    -- Get parent roles recursively
    SELECT tr.id AS role_id, tr.parent_role_id
    FROM tenant_roles tr
    JOIN role_hierarchy rh ON tr.id = rh.parent_role_id
)
SELECT COUNT(*) > 0 AS has_permission
FROM role_hierarchy rh
JOIN tenant_role_permissions trp ON rh.role_id = trp.tenant_role_id
JOIN permissions p ON trp.permission_id = p.id
WHERE p.code = $3
AND trp.is_active = TRUE AND p.is_active = TRUE
AND (trp.scope_id = $4 OR $4::integer IS NULL OR trp.scope_id IS NULL)
`

type CheckUserPermissionParams struct {
	UserID   int32         `json:"user_id"`
	TenantID int32         `json:"tenant_id"`
	Code     string        `json:"code"`
	ScopeID  sql.NullInt32 `json:"scope_id"`
	BranchID sql.NullInt32 `json:"branch_id"`
}

func (q *Queries) CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserPermission,
		arg.UserID,
		arg.TenantID,
		arg.Code,
		arg.ScopeID,
		arg.BranchID,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const countTenantUsers = `-- name: CountTenantUsers :one
SELECT COUNT(*) FROM users
WHERE tenants_id = $1 AND is_active = true
`

func (q *Queries) CountTenantUsers(ctx context.Context, tenantsID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenantUsers, tenantsID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO rbac_audit_log (
    action, actor_id, target_user_id, target_role_id, permission_id,
    old_values, new_values, reason, ip_address, user_agent, tenant_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, action, actor_id, target_user_id, target_role_id, permission_id, old_values, new_values, reason, ip_address, user_agent, tenant_id, created_at
`

type CreateAuditLogParams struct {
	Action       string                `json:"action"`
	ActorID      int32                 `json:"actor_id"`
	TargetUserID sql.NullInt32         `json:"target_user_id"`
	TargetRoleID sql.NullInt32         `json:"target_role_id"`
	PermissionID sql.NullInt32         `json:"permission_id"`
	OldValues    pqtype.NullRawMessage `json:"old_values"`
	NewValues    pqtype.NullRawMessage `json:"new_values"`
	Reason       sql.NullString        `json:"reason"`
	IpAddress    string                `json:"ip_address"`
	UserAgent    string                `json:"user_agent"`
	TenantID     int32                 `json:"tenant_id"`
}

// ========================================
// AUDIT LOG QUERIES
// ========================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (RbacAuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.Action,
		arg.ActorID,
		arg.TargetUserID,
		arg.TargetRoleID,
		arg.PermissionID,
		arg.OldValues,
		arg.NewValues,
		arg.Reason,
		arg.IpAddress,
		arg.UserAgent,
		arg.TenantID,
	)
	var i RbacAuditLog
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ActorID,
		&i.TargetUserID,
		&i.TargetRoleID,
		&i.PermissionID,
		&i.OldValues,
		&i.NewValues,
		&i.Reason,
		&i.IpAddress,
		&i.UserAgent,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (code, description, module, action, resource, scope)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, description, module, action, resource, scope, is_active, created_at
`

type CreatePermissionParams struct {
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	Module      string         `json:"module"`
	Action      string         `json:"action"`
	Resource    sql.NullString `json:"resource"`
	Scope       string         `json:"scope"`
}

// ========================================
// PERMISSION QUERIES
// ========================================
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission,
		arg.Code,
		arg.Description,
		arg.Module,
		arg.Action,
		arg.Resource,
		arg.Scope,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.Action,
		&i.Resource,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantRole = `-- name: CreateTenantRole :one


INSERT INTO tenant_roles (
    tenant_id, name, description, parent_role_id, is_default, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, name, description, parent_role_id, level, is_default, is_active, metadata, created_at, updated_at
`

type CreateTenantRoleParams struct {
	TenantID     int32                 `json:"tenant_id"`
	Name         string                `json:"name"`
	Description  sql.NullString        `json:"description"`
	ParentRoleID sql.NullInt32         `json:"parent_role_id"`
	IsDefault    sql.NullBool          `json:"is_default"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

// RBAC System Database Queries
// Queries for managing roles, permissions, and user assignments in the RBAC system
// Focus: User roles under tenants (no tenant-level roles)
// ========================================
// TENANT ROLES QUERIES (User roles per tenant)
// ========================================
func (q *Queries) CreateTenantRole(ctx context.Context, arg CreateTenantRoleParams) (TenantRole, error) {
	row := q.db.QueryRowContext(ctx, createTenantRole,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.ParentRoleID,
		arg.IsDefault,
		arg.Metadata,
	)
	var i TenantRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.Level,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    tenants_id, business_id, branch_id, email, password_hash,
    first_name, last_name, phone, is_active, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, business_id, tenants_id, branch_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, last_login_at, email_verified, verification_code, verification_expires_at, metadata, created_at, updated_at
`

type CreateUserParams struct {
	TenantsID    int32                 `json:"tenants_id"`
	BusinessID   sql.NullInt32         `json:"business_id"`
	BranchID     sql.NullInt32         `json:"branch_id"`
	Email        string                `json:"email"`
	PasswordHash string                `json:"password_hash"`
	FirstName    sql.NullString        `json:"first_name"`
	LastName     sql.NullString        `json:"last_name"`
	Phone        sql.NullString        `json:"phone"`
	IsActive     bool                  `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

// ========================================
// USER MANAGEMENT QUERIES (ENHANCED)
// ========================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.TenantsID,
		arg.BusinessID,
		arg.BranchID,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.IsActive,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantsID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenants_id = $2
RETURNING id, business_id, tenants_id, branch_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, last_login_at, email_verified, verification_code, verification_expires_at, metadata, created_at, updated_at
`

type DeactivateUserParams struct {
	ID        int32 `json:"id"`
	TenantsID int32 `json:"tenants_id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, arg.ID, arg.TenantsID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantsID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTenantRole = `-- name: DeleteTenantRole :exec
DELETE FROM tenant_roles
WHERE id = $1 AND tenant_id = $2
`

type DeleteTenantRoleParams struct {
	ID       int32 `json:"id"`
	TenantID int32 `json:"tenant_id"`
}

func (q *Queries) DeleteTenantRole(ctx context.Context, arg DeleteTenantRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteTenantRole, arg.ID, arg.TenantID)
	return err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT al.id, al.action, al.actor_id, al.target_user_id, al.target_role_id, al.permission_id, al.old_values, al.new_values, al.reason, al.ip_address, al.user_agent, al.tenant_id, al.created_at,
       a.email as actor_email, a.first_name as actor_first_name, a.last_name as actor_last_name,
       tu.email as target_user_email, tu.first_name as target_first_name, tu.last_name as target_last_name,
       tr.name as target_role_name,
       p.code as permission_code
FROM rbac_audit_log al
LEFT JOIN users a ON al.actor_id = a.id
LEFT JOIN users tu ON al.target_user_id = tu.id
LEFT JOIN tenant_roles tr ON al.target_role_id = tr.id
LEFT JOIN permissions p ON al.permission_id = p.id
WHERE al.tenant_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuditLogsParams struct {
	TenantID int32 `json:"tenant_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type GetAuditLogsRow struct {
	ID              int32                 `json:"id"`
	Action          string                `json:"action"`
	ActorID         int32                 `json:"actor_id"`
	TargetUserID    sql.NullInt32         `json:"target_user_id"`
	TargetRoleID    sql.NullInt32         `json:"target_role_id"`
	PermissionID    sql.NullInt32         `json:"permission_id"`
	OldValues       pqtype.NullRawMessage `json:"old_values"`
	NewValues       pqtype.NullRawMessage `json:"new_values"`
	Reason          sql.NullString        `json:"reason"`
	IpAddress       string                `json:"ip_address"`
	UserAgent       string                `json:"user_agent"`
	TenantID        int32                 `json:"tenant_id"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	ActorEmail      sql.NullString        `json:"actor_email"`
	ActorFirstName  sql.NullString        `json:"actor_first_name"`
	ActorLastName   sql.NullString        `json:"actor_last_name"`
	TargetUserEmail sql.NullString        `json:"target_user_email"`
	TargetFirstName sql.NullString        `json:"target_first_name"`
	TargetLastName  sql.NullString        `json:"target_last_name"`
	TargetRoleName  sql.NullString        `json:"target_role_name"`
	PermissionCode  sql.NullString        `json:"permission_code"`
}

func (q *Queries) GetAuditLogs(ctx context.Context, arg GetAuditLogsParams) ([]GetAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuditLogsRow{}
	for rows.Next() {
		var i GetAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ActorID,
			&i.TargetUserID,
			&i.TargetRoleID,
			&i.PermissionID,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.TenantID,
			&i.CreatedAt,
			&i.ActorEmail,
			&i.ActorFirstName,
			&i.ActorLastName,
			&i.TargetUserEmail,
			&i.TargetFirstName,
			&i.TargetLastName,
			&i.TargetRoleName,
			&i.PermissionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildRoles = `-- name: GetChildRoles :many
WITH RECURSIVE child_roles AS (
    -- Start from the given role
    SELECT tr.id, tr.tenant_id, tr.name, tr.parent_role_id, tr.level, 0 as depth
    FROM tenant_roles tr
    WHERE tr.id = $1 AND tr.tenant_id = $2

    UNION ALL

    -- Get child roles recursively
    SELECT tr.id, tr.tenant_id, tr.name, tr.parent_role_id, tr.level, cr.depth + 1
    FROM tenant_roles tr
    JOIN child_roles cr ON tr.parent_role_id = cr.id
    WHERE cr.depth < 10
)
SELECT id, tenant_id, name, parent_role_id, level, depth FROM child_roles
WHERE depth > 0
ORDER BY depth, level
`

type GetChildRolesParams struct {
	ID       int32 `json:"id"`
	TenantID int32 `json:"tenant_id"`
}

type GetChildRolesRow struct {
	ID           int32         `json:"id"`
	TenantID     int32         `json:"tenant_id"`
	Name         string        `json:"name"`
	ParentRoleID sql.NullInt32 `json:"parent_role_id"`
	Level        int32         `json:"level"`
	Depth        int32         `json:"depth"`
}

func (q *Queries) GetChildRoles(ctx context.Context, arg GetChildRolesParams) ([]GetChildRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getChildRoles, arg.ID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildRolesRow{}
	for rows.Next() {
		var i GetChildRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentRoleID,
			&i.Level,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, description, module, action, resource, scope, is_active, created_at FROM permissions
WHERE code = $1 AND is_active = true
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.Action,
		&i.Resource,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, code, description, module, action, resource, scope, is_active, created_at FROM permissions
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetPermissionByID(ctx context.Context, id int32) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.Action,
		&i.Resource,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionRoles = `-- name: GetPermissionRoles :many
SELECT trp.id, trp.tenant_role_id, trp.permission_id, trp.scope_type, trp.scope_id, trp.granted_by, trp.granted_at, trp.is_active, trp.metadata, tr.name as role_name, tr.description as role_description
FROM tenant_role_permissions trp
JOIN tenant_roles tr ON trp.tenant_role_id = tr.id
WHERE trp.permission_id = $1 AND trp.is_active = true
ORDER BY tr.level, tr.name
`

type GetPermissionRolesRow struct {
	ID              int32                 `json:"id"`
	TenantRoleID    int32                 `json:"tenant_role_id"`
	PermissionID    int32                 `json:"permission_id"`
	ScopeType       sql.NullString        `json:"scope_type"`
	ScopeID         sql.NullInt32         `json:"scope_id"`
	GrantedBy       sql.NullInt32         `json:"granted_by"`
	GrantedAt       sql.NullTime          `json:"granted_at"`
	IsActive        sql.NullBool          `json:"is_active"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	RoleName        string                `json:"role_name"`
	RoleDescription sql.NullString        `json:"role_description"`
}

func (q *Queries) GetPermissionRoles(ctx context.Context, permissionID int32) ([]GetPermissionRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPermissionRoles, permissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPermissionRolesRow{}
	for rows.Next() {
		var i GetPermissionRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantRoleID,
			&i.PermissionID,
			&i.ScopeType,
			&i.ScopeID,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.IsActive,
			&i.Metadata,
			&i.RoleName,
			&i.RoleDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleHierarchy = `-- name: GetRoleHierarchy :many
WITH RECURSIVE role_hierarchy AS (
    -- Start from the given role
    SELECT tr.id, tr.tenant_id, tr.name, tr.parent_role_id, tr.level, 0 as depth, ARRAY[tr.id] as path
    FROM tenant_roles tr
    WHERE tr.id = $1 AND tr.tenant_id = $2

    UNION ALL

    -- Get parent roles recursively
    SELECT tr.id, tr.tenant_id, tr.name, tr.parent_role_id, tr.level, rh.depth + 1, rh.path || tr.id
    FROM tenant_roles tr
    JOIN role_hierarchy rh ON tr.id = rh.parent_role_id
    WHERE rh.depth < 10 AND NOT tr.id = ANY(rh.path) -- prevent cycles
)
SELECT id, tenant_id, name, parent_role_id, level, depth, path FROM role_hierarchy
ORDER BY depth
`

type GetRoleHierarchyParams struct {
	ID       int32 `json:"id"`
	TenantID int32 `json:"tenant_id"`
}

type GetRoleHierarchyRow struct {
	ID           int32         `json:"id"`
	TenantID     int32         `json:"tenant_id"`
	Name         string        `json:"name"`
	ParentRoleID sql.NullInt32 `json:"parent_role_id"`
	Level        int32         `json:"level"`
	Depth        int32         `json:"depth"`
	Path         interface{}   `json:"path"`
}

func (q *Queries) GetRoleHierarchy(ctx context.Context, arg GetRoleHierarchyParams) ([]GetRoleHierarchyRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoleHierarchy, arg.ID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoleHierarchyRow{}
	for rows.Next() {
		var i GetRoleHierarchyRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentRoleID,
			&i.Level,
			&i.Depth,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT trp.id, trp.tenant_role_id, trp.permission_id, trp.scope_type, trp.scope_id, trp.granted_by, trp.granted_at, trp.is_active, trp.metadata, p.code, p.description, p.module, p.action, p.resource
FROM tenant_role_permissions trp
JOIN permissions p ON trp.permission_id = p.id
WHERE trp.tenant_role_id = $1 AND trp.is_active = true
ORDER BY p.module, p.action, p.resource
`

type GetRolePermissionsRow struct {
	ID           int32                 `json:"id"`
	TenantRoleID int32                 `json:"tenant_role_id"`
	PermissionID int32                 `json:"permission_id"`
	ScopeType    sql.NullString        `json:"scope_type"`
	ScopeID      sql.NullInt32         `json:"scope_id"`
	GrantedBy    sql.NullInt32         `json:"granted_by"`
	GrantedAt    sql.NullTime          `json:"granted_at"`
	IsActive     sql.NullBool          `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	Code         string                `json:"code"`
	Description  sql.NullString        `json:"description"`
	Module       string                `json:"module"`
	Action       string                `json:"action"`
	Resource     sql.NullString        `json:"resource"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, tenantRoleID int32) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissions, tenantRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolePermissionsRow{}
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantRoleID,
			&i.PermissionID,
			&i.ScopeType,
			&i.ScopeID,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.IsActive,
			&i.Metadata,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.Action,
			&i.Resource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleUsers = `-- name: GetRoleUsers :many
SELECT ura.id, ura.user_id, ura.tenant_role_id, ura.business_id, ura.branch_id, ura.assigned_by, ura.assigned_at, ura.expires_at, ura.is_active, ura.metadata, u.email, u.first_name, u.last_name,
       b.name as business_name, br.name as branch_name
FROM user_role_assignments ura
JOIN users u ON ura.user_id = u.id
LEFT JOIN businesses b ON ura.business_id = b.id
LEFT JOIN branches br ON ura.branch_id = br.id
WHERE ura.tenant_role_id = $1 AND ura.is_active = true
AND (ura.expires_at IS NULL OR ura.expires_at > NOW())
ORDER BY u.email
`

type GetRoleUsersRow struct {
	ID           int32                 `json:"id"`
	UserID       int32                 `json:"user_id"`
	TenantRoleID int32                 `json:"tenant_role_id"`
	BusinessID   sql.NullInt32         `json:"business_id"`
	BranchID     sql.NullInt32         `json:"branch_id"`
	AssignedBy   sql.NullInt32         `json:"assigned_by"`
	AssignedAt   sql.NullTime          `json:"assigned_at"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	IsActive     sql.NullBool          `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	Email        string                `json:"email"`
	FirstName    sql.NullString        `json:"first_name"`
	LastName     sql.NullString        `json:"last_name"`
	BusinessName sql.NullString        `json:"business_name"`
	BranchName   sql.NullString        `json:"branch_name"`
}

func (q *Queries) GetRoleUsers(ctx context.Context, tenantRoleID int32) ([]GetRoleUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoleUsers, tenantRoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoleUsersRow{}
	for rows.Next() {
		var i GetRoleUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantRoleID,
			&i.BusinessID,
			&i.BranchID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.IsActive,
			&i.Metadata,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.BusinessName,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantRoleByID = `-- name: GetTenantRoleByID :one
SELECT id, tenant_id, name, description, parent_role_id, level, is_default, is_active, metadata, created_at, updated_at FROM tenant_roles
WHERE id = $1 AND tenant_id = $2
`

type GetTenantRoleByIDParams struct {
	ID       int32 `json:"id"`
	TenantID int32 `json:"tenant_id"`
}

func (q *Queries) GetTenantRoleByID(ctx context.Context, arg GetTenantRoleByIDParams) (TenantRole, error) {
	row := q.db.QueryRowContext(ctx, getTenantRoleByID, arg.ID, arg.TenantID)
	var i TenantRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.Level,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantRoleByName = `-- name: GetTenantRoleByName :one
SELECT id, tenant_id, name, description, parent_role_id, level, is_default, is_active, metadata, created_at, updated_at FROM tenant_roles
WHERE name = $1 AND tenant_id = $2
`

type GetTenantRoleByNameParams struct {
	Name     string `json:"name"`
	TenantID int32  `json:"tenant_id"`
}

func (q *Queries) GetTenantRoleByName(ctx context.Context, arg GetTenantRoleByNameParams) (TenantRole, error) {
	row := q.db.QueryRowContext(ctx, getTenantRoleByName, arg.Name, arg.TenantID)
	var i TenantRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.Level,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAuditLogs = `-- name: GetUserAuditLogs :many
SELECT al.id, al.action, al.actor_id, al.target_user_id, al.target_role_id, al.permission_id, al.old_values, al.new_values, al.reason, al.ip_address, al.user_agent, al.tenant_id, al.created_at,
       a.email as actor_email, a.first_name as actor_first_name, a.last_name as actor_last_name,
       tr.name as target_role_name,
       p.code as permission_code
FROM rbac_audit_log al
LEFT JOIN users a ON al.actor_id = a.id
LEFT JOIN tenant_roles tr ON al.target_role_id = tr.id
LEFT JOIN permissions p ON al.permission_id = p.id
WHERE al.target_user_id = $1 AND al.tenant_id = $2
ORDER BY al.created_at DESC
LIMIT $3 OFFSET $4
`

type GetUserAuditLogsParams struct {
	TargetUserID sql.NullInt32 `json:"target_user_id"`
	TenantID     int32         `json:"tenant_id"`
	Limit        int32         `json:"limit"`
	Offset       int32         `json:"offset"`
}

type GetUserAuditLogsRow struct {
	ID             int32                 `json:"id"`
	Action         string                `json:"action"`
	ActorID        int32                 `json:"actor_id"`
	TargetUserID   sql.NullInt32         `json:"target_user_id"`
	TargetRoleID   sql.NullInt32         `json:"target_role_id"`
	PermissionID   sql.NullInt32         `json:"permission_id"`
	OldValues      pqtype.NullRawMessage `json:"old_values"`
	NewValues      pqtype.NullRawMessage `json:"new_values"`
	Reason         sql.NullString        `json:"reason"`
	IpAddress      string                `json:"ip_address"`
	UserAgent      string                `json:"user_agent"`
	TenantID       int32                 `json:"tenant_id"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	ActorEmail     sql.NullString        `json:"actor_email"`
	ActorFirstName sql.NullString        `json:"actor_first_name"`
	ActorLastName  sql.NullString        `json:"actor_last_name"`
	TargetRoleName sql.NullString        `json:"target_role_name"`
	PermissionCode sql.NullString        `json:"permission_code"`
}

func (q *Queries) GetUserAuditLogs(ctx context.Context, arg GetUserAuditLogsParams) ([]GetUserAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAuditLogs,
		arg.TargetUserID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAuditLogsRow{}
	for rows.Next() {
		var i GetUserAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ActorID,
			&i.TargetUserID,
			&i.TargetRoleID,
			&i.PermissionID,
			&i.OldValues,
			&i.NewValues,
			&i.Reason,
			&i.IpAddress,
			&i.UserAgent,
			&i.TenantID,
			&i.CreatedAt,
			&i.ActorEmail,
			&i.ActorFirstName,
			&i.ActorLastName,
			&i.TargetRoleName,
			&i.PermissionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.business_id, u.tenants_id, u.branch_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.last_login_at, u.email_verified, u.verification_code, u.verification_expires_at, u.metadata, u.created_at, u.updated_at, t.organization as tenant_name, b.name as business_name, br.name as branch_name
FROM users u
JOIN tenants t ON u.tenants_id = t.id
LEFT JOIN businesses b ON u.business_id = b.id
LEFT JOIN branches br ON u.branch_id = br.id
WHERE u.email = $1 AND u.tenants_id = $2
`

type GetUserByEmailParams struct {
	Email     string `json:"email"`
	TenantsID int32  `json:"tenants_id"`
}

type GetUserByEmailRow struct {
	ID                    int32                 `json:"id"`
	BusinessID            sql.NullInt32         `json:"business_id"`
	TenantsID             int32                 `json:"tenants_id"`
	BranchID              sql.NullInt32         `json:"branch_id"`
	Email                 string                `json:"email"`
	PasswordHash          string                `json:"password_hash"`
	FirstName             sql.NullString        `json:"first_name"`
	LastName              sql.NullString        `json:"last_name"`
	Phone                 sql.NullString        `json:"phone"`
	AvatarUrl             sql.NullString        `json:"avatar_url"`
	IsActive              bool                  `json:"is_active"`
	LastLoginAt           sql.NullTime          `json:"last_login_at"`
	EmailVerified         sql.NullBool          `json:"email_verified"`
	VerificationCode      sql.NullString        `json:"verification_code"`
	VerificationExpiresAt sql.NullTime          `json:"verification_expires_at"`
	Metadata              pqtype.NullRawMessage `json:"metadata"`
	CreatedAt             sql.NullTime          `json:"created_at"`
	UpdatedAt             sql.NullTime          `json:"updated_at"`
	TenantName            string                `json:"tenant_name"`
	BusinessName          sql.NullString        `json:"business_name"`
	BranchName            sql.NullString        `json:"branch_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.Email, arg.TenantsID)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantsID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantName,
		&i.BusinessName,
		&i.BranchName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.business_id, u.tenants_id, u.branch_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.last_login_at, u.email_verified, u.verification_code, u.verification_expires_at, u.metadata, u.created_at, u.updated_at, t.organization as tenant_name, b.name as business_name, br.name as branch_name
FROM users u
JOIN tenants t ON u.tenants_id = t.id
LEFT JOIN businesses b ON u.business_id = b.id
LEFT JOIN branches br ON u.branch_id = br.id
WHERE u.id = $1 AND u.tenants_id = $2
`

type GetUserByIDParams struct {
	ID        int32 `json:"id"`
	TenantsID int32 `json:"tenants_id"`
}

type GetUserByIDRow struct {
	ID                    int32                 `json:"id"`
	BusinessID            sql.NullInt32         `json:"business_id"`
	TenantsID             int32                 `json:"tenants_id"`
	BranchID              sql.NullInt32         `json:"branch_id"`
	Email                 string                `json:"email"`
	PasswordHash          string                `json:"password_hash"`
	FirstName             sql.NullString        `json:"first_name"`
	LastName              sql.NullString        `json:"last_name"`
	Phone                 sql.NullString        `json:"phone"`
	AvatarUrl             sql.NullString        `json:"avatar_url"`
	IsActive              bool                  `json:"is_active"`
	LastLoginAt           sql.NullTime          `json:"last_login_at"`
	EmailVerified         sql.NullBool          `json:"email_verified"`
	VerificationCode      sql.NullString        `json:"verification_code"`
	VerificationExpiresAt sql.NullTime          `json:"verification_expires_at"`
	Metadata              pqtype.NullRawMessage `json:"metadata"`
	CreatedAt             sql.NullTime          `json:"created_at"`
	UpdatedAt             sql.NullTime          `json:"updated_at"`
	TenantName            string                `json:"tenant_name"`
	BusinessName          sql.NullString        `json:"business_name"`
	BranchName            sql.NullString        `json:"branch_name"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, arg.ID, arg.TenantsID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantsID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantName,
		&i.BusinessName,
		&i.BranchName,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many

SELECT DISTINCT p.id, p.code, p.description, p.module, p.action, p.resource,
       trp.scope_type, trp.scope_id, tr.name as role_name
FROM users u
JOIN user_role_assignments ura ON u.id = ura.user_id
JOIN tenant_roles tr ON ura.tenant_role_id = tr.id
JOIN tenant_role_permissions trp ON tr.id = trp.tenant_role_id
JOIN permissions p ON trp.permission_id = p.id
WHERE u.id = $1 AND u.tenants_id = $2
AND ura.is_active = true AND trp.is_active = true AND p.is_active = true
AND (ura.expires_at IS NULL OR ura.expires_at > NOW())
ORDER BY p.module, p.action, p.resource
`

type GetUserPermissionsParams struct {
	ID        int32 `json:"id"`
	TenantsID int32 `json:"tenants_id"`
}

type GetUserPermissionsRow struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	Module      string         `json:"module"`
	Action      string         `json:"action"`
	Resource    sql.NullString `json:"resource"`
	ScopeType   sql.NullString `json:"scope_type"`
	ScopeID     sql.NullInt32  `json:"scope_id"`
	RoleName    string         `json:"role_name"`
}

// ========================================
// USER PERMISSION QUERIES (AGGREGATED)
// ========================================
func (q *Queries) GetUserPermissions(ctx context.Context, arg GetUserPermissionsParams) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, arg.ID, arg.TenantsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.Action,
			&i.Resource,
			&i.ScopeType,
			&i.ScopeID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionsWithHierarchy = `-- name: GetUserPermissionsWithHierarchy :many
WITH RECURSIVE role_hierarchy AS (
    -- Get direct role assignments for the user
    SELECT DISTINCT tr.id as role_id, tr.name as role_name, tr.parent_role_id, 0 as level
    FROM tenant_roles tr
    JOIN user_role_assignments ura ON tr.id = ura.tenant_role_id
    WHERE ura.user_id = $1 AND tr.tenant_id = $2
    AND ura.is_active = TRUE
    AND (ura.expires_at IS NULL OR ura.expires_at > NOW())

    UNION ALL

    -- Get parent roles recursively
    SELECT tr.id as role_id, tr.name as role_name, tr.parent_role_id, rh.level + 1
    FROM tenant_roles tr
    JOIN role_hierarchy rh ON tr.id = rh.parent_role_id
    WHERE rh.level < 10 -- prevent infinite recursion
)
SELECT DISTINCT
    p.id, p.code, p.description, p.module, p.action, p.resource,
    trp.scope_type, trp.scope_id, rh.role_name
FROM role_hierarchy rh
JOIN tenant_role_permissions trp ON rh.role_id = trp.tenant_role_id
JOIN permissions p ON trp.permission_id = p.id
WHERE trp.is_active = TRUE AND p.is_active = TRUE
ORDER BY p.module, p.action, p.resource
`

type GetUserPermissionsWithHierarchyParams struct {
	UserID   int32 `json:"user_id"`
	TenantID int32 `json:"tenant_id"`
}

type GetUserPermissionsWithHierarchyRow struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	Module      string         `json:"module"`
	Action      string         `json:"action"`
	Resource    sql.NullString `json:"resource"`
	ScopeType   sql.NullString `json:"scope_type"`
	ScopeID     sql.NullInt32  `json:"scope_id"`
	RoleName    string         `json:"role_name"`
}

func (q *Queries) GetUserPermissionsWithHierarchy(ctx context.Context, arg GetUserPermissionsWithHierarchyParams) ([]GetUserPermissionsWithHierarchyRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissionsWithHierarchy, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsWithHierarchyRow{}
	for rows.Next() {
		var i GetUserPermissionsWithHierarchyRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.Action,
			&i.Resource,
			&i.ScopeType,
			&i.ScopeID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleAssignment = `-- name: GetUserRoleAssignment :one
SELECT ura.id, ura.user_id, ura.tenant_role_id, ura.business_id, ura.branch_id, ura.assigned_by, ura.assigned_at, ura.expires_at, ura.is_active, ura.metadata, tr.name as role_name
FROM user_role_assignments ura
JOIN tenant_roles tr ON ura.tenant_role_id = tr.id
WHERE ura.user_id = $1 AND ura.tenant_role_id = $2
AND (ura.business_id = $3 OR ($3::integer IS NULL AND ura.business_id IS NULL))
AND (ura.branch_id = $4 OR ($4::integer IS NULL AND ura.branch_id IS NULL))
AND ura.is_active = true
`

type GetUserRoleAssignmentParams struct {
	UserID       int32         `json:"user_id"`
	TenantRoleID int32         `json:"tenant_role_id"`
	BusinessID   sql.NullInt32 `json:"business_id"`
	BranchID     sql.NullInt32 `json:"branch_id"`
}

type GetUserRoleAssignmentRow struct {
	ID           int32                 `json:"id"`
	UserID       int32                 `json:"user_id"`
	TenantRoleID int32                 `json:"tenant_role_id"`
	BusinessID   sql.NullInt32         `json:"business_id"`
	BranchID     sql.NullInt32         `json:"branch_id"`
	AssignedBy   sql.NullInt32         `json:"assigned_by"`
	AssignedAt   sql.NullTime          `json:"assigned_at"`
	ExpiresAt    sql.NullTime          `json:"expires_at"`
	IsActive     sql.NullBool          `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	RoleName     string                `json:"role_name"`
}

func (q *Queries) GetUserRoleAssignment(ctx context.Context, arg GetUserRoleAssignmentParams) (GetUserRoleAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleAssignment,
		arg.UserID,
		arg.TenantRoleID,
		arg.BusinessID,
		arg.BranchID,
	)
	var i GetUserRoleAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantRoleID,
		&i.BusinessID,
		&i.BranchID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.Metadata,
		&i.RoleName,
	)
	return i, err
}

const getUserRoleAssignments = `-- name: GetUserRoleAssignments :many
SELECT ura.id, ura.user_id, ura.tenant_role_id, ura.business_id, ura.branch_id, ura.assigned_by, ura.assigned_at, ura.expires_at, ura.is_active, ura.metadata, tr.name as role_name, tr.description as role_description,
       b.name as business_name, br.name as branch_name
FROM user_role_assignments ura
JOIN tenant_roles tr ON ura.tenant_role_id = tr.id
LEFT JOIN businesses b ON ura.business_id = b.id
LEFT JOIN branches br ON ura.branch_id = br.id
WHERE ura.user_id = $1 AND ura.is_active = true
AND (ura.expires_at IS NULL OR ura.expires_at > NOW())
ORDER BY ura.assigned_at DESC
`

type GetUserRoleAssignmentsRow struct {
	ID              int32                 `json:"id"`
	UserID          int32                 `json:"user_id"`
	TenantRoleID    int32                 `json:"tenant_role_id"`
	BusinessID      sql.NullInt32         `json:"business_id"`
	BranchID        sql.NullInt32         `json:"branch_id"`
	AssignedBy      sql.NullInt32         `json:"assigned_by"`
	AssignedAt      sql.NullTime          `json:"assigned_at"`
	ExpiresAt       sql.NullTime          `json:"expires_at"`
	IsActive        sql.NullBool          `json:"is_active"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	RoleName        string                `json:"role_name"`
	RoleDescription sql.NullString        `json:"role_description"`
	BusinessName    sql.NullString        `json:"business_name"`
	BranchName      sql.NullString        `json:"branch_name"`
}

func (q *Queries) GetUserRoleAssignments(ctx context.Context, userID int32) ([]GetUserRoleAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoleAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRoleAssignmentsRow{}
	for rows.Next() {
		var i GetUserRoleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantRoleID,
			&i.BusinessID,
			&i.BranchID,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.ExpiresAt,
			&i.IsActive,
			&i.Metadata,
			&i.RoleName,
			&i.RoleDescription,
			&i.BusinessName,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantPermissionToRole = `-- name: GrantPermissionToRole :one

INSERT INTO tenant_role_permissions (
    tenant_role_id, permission_id, scope_type, scope_id, granted_by, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_role_id, permission_id, scope_type, scope_id, granted_by, granted_at, is_active, metadata
`

type GrantPermissionToRoleParams struct {
	TenantRoleID int32                 `json:"tenant_role_id"`
	PermissionID int32                 `json:"permission_id"`
	ScopeType    sql.NullString        `json:"scope_type"`
	ScopeID      sql.NullInt32         `json:"scope_id"`
	GrantedBy    sql.NullInt32         `json:"granted_by"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

// ========================================
// TENANT ROLE PERMISSIONS QUERIES
// ========================================
func (q *Queries) GrantPermissionToRole(ctx context.Context, arg GrantPermissionToRoleParams) (TenantRolePermission, error) {
	row := q.db.QueryRowContext(ctx, grantPermissionToRole,
		arg.TenantRoleID,
		arg.PermissionID,
		arg.ScopeType,
		arg.ScopeID,
		arg.GrantedBy,
		arg.Metadata,
	)
	var i TenantRolePermission
	err := row.Scan(
		&i.ID,
		&i.TenantRoleID,
		&i.PermissionID,
		&i.ScopeType,
		&i.ScopeID,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.IsActive,
		&i.Metadata,
	)
	return i, err
}

const listBranchUsers = `-- name: ListBranchUsers :many
SELECT u.id, u.business_id, u.tenants_id, u.branch_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.last_login_at, u.email_verified, u.verification_code, u.verification_expires_at, u.metadata, u.created_at, u.updated_at, t.organization as tenant_name, b.name as business_name, br.name as branch_name
FROM users u
JOIN tenants t ON u.tenants_id = t.id
LEFT JOIN businesses b ON u.business_id = b.id
LEFT JOIN branches br ON u.branch_id = br.id
WHERE u.tenants_id = $1 AND u.branch_id = $2 AND u.is_active = true
ORDER BY u.created_at DESC
`

type ListBranchUsersParams struct {
	TenantsID int32         `json:"tenants_id"`
	BranchID  sql.NullInt32 `json:"branch_id"`
}

type ListBranchUsersRow struct {
	ID                    int32                 `json:"id"`
	BusinessID            sql.NullInt32         `json:"business_id"`
	TenantsID             int32                 `json:"tenants_id"`
	BranchID              sql.NullInt32         `json:"branch_id"`
	Email                 string                `json:"email"`
	PasswordHash          string                `json:"password_hash"`
	FirstName             sql.NullString        `json:"first_name"`
	LastName              sql.NullString        `json:"last_name"`
	Phone                 sql.NullString        `json:"phone"`
	AvatarUrl             sql.NullString        `json:"avatar_url"`
	IsActive              bool                  `json:"is_active"`
	LastLoginAt           sql.NullTime          `json:"last_login_at"`
	EmailVerified         sql.NullBool          `json:"email_verified"`
	VerificationCode      sql.NullString        `json:"verification_code"`
	VerificationExpiresAt sql.NullTime          `json:"verification_expires_at"`
	Metadata              pqtype.NullRawMessage `json:"metadata"`
	CreatedAt             sql.NullTime          `json:"created_at"`
	UpdatedAt             sql.NullTime          `json:"updated_at"`
	TenantName            string                `json:"tenant_name"`
	BusinessName          sql.NullString        `json:"business_name"`
	BranchName            sql.NullString        `json:"branch_name"`
}

func (q *Queries) ListBranchUsers(ctx context.Context, arg ListBranchUsersParams) ([]ListBranchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listBranchUsers, arg.TenantsID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchUsersRow{}
	for rows.Next() {
		var i ListBranchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.TenantsID,
			&i.BranchID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.LastLoginAt,
			&i.EmailVerified,
			&i.VerificationCode,
			&i.VerificationExpiresAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantName,
			&i.BusinessName,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessUsers = `-- name: ListBusinessUsers :many
SELECT u.id, u.business_id, u.tenants_id, u.branch_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.last_login_at, u.email_verified, u.verification_code, u.verification_expires_at, u.metadata, u.created_at, u.updated_at, t.organization as tenant_name, b.name as business_name, br.name as branch_name
FROM users u
JOIN tenants t ON u.tenants_id = t.id
LEFT JOIN businesses b ON u.business_id = b.id
LEFT JOIN branches br ON u.branch_id = br.id
WHERE u.tenants_id = $1 AND u.business_id = $2 AND u.is_active = true
ORDER BY u.created_at DESC
`

type ListBusinessUsersParams struct {
	TenantsID  int32         `json:"tenants_id"`
	BusinessID sql.NullInt32 `json:"business_id"`
}

type ListBusinessUsersRow struct {
	ID                    int32                 `json:"id"`
	BusinessID            sql.NullInt32         `json:"business_id"`
	TenantsID             int32                 `json:"tenants_id"`
	BranchID              sql.NullInt32         `json:"branch_id"`
	Email                 string                `json:"email"`
	PasswordHash          string                `json:"password_hash"`
	FirstName             sql.NullString        `json:"first_name"`
	LastName              sql.NullString        `json:"last_name"`
	Phone                 sql.NullString        `json:"phone"`
	AvatarUrl             sql.NullString        `json:"avatar_url"`
	IsActive              bool                  `json:"is_active"`
	LastLoginAt           sql.NullTime          `json:"last_login_at"`
	EmailVerified         sql.NullBool          `json:"email_verified"`
	VerificationCode      sql.NullString        `json:"verification_code"`
	VerificationExpiresAt sql.NullTime          `json:"verification_expires_at"`
	Metadata              pqtype.NullRawMessage `json:"metadata"`
	CreatedAt             sql.NullTime          `json:"created_at"`
	UpdatedAt             sql.NullTime          `json:"updated_at"`
	TenantName            string                `json:"tenant_name"`
	BusinessName          sql.NullString        `json:"business_name"`
	BranchName            sql.NullString        `json:"branch_name"`
}

func (q *Queries) ListBusinessUsers(ctx context.Context, arg ListBusinessUsersParams) ([]ListBusinessUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listBusinessUsers, arg.TenantsID, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessUsersRow{}
	for rows.Next() {
		var i ListBusinessUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.TenantsID,
			&i.BranchID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.LastLoginAt,
			&i.EmailVerified,
			&i.VerificationCode,
			&i.VerificationExpiresAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantName,
			&i.BusinessName,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, description, module, action, resource, scope, is_active, created_at FROM permissions
WHERE is_active = true
ORDER BY module, action, resource
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.Action,
			&i.Resource,
			&i.Scope,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByModule = `-- name: ListPermissionsByModule :many
SELECT id, code, description, module, action, resource, scope, is_active, created_at FROM permissions
WHERE module = $1 AND is_active = true
ORDER BY action, resource
`

func (q *Queries) ListPermissionsByModule(ctx context.Context, module string) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByModule, module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.Action,
			&i.Resource,
			&i.Scope,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantRoles = `-- name: ListTenantRoles :many
SELECT id, tenant_id, name, description, parent_role_id, level, is_default, is_active, metadata, created_at, updated_at FROM tenant_roles
WHERE tenant_id = $1 AND is_active = true
ORDER BY level ASC, name ASC
`

func (q *Queries) ListTenantRoles(ctx context.Context, tenantID int32) ([]TenantRole, error) {
	rows, err := q.db.QueryContext(ctx, listTenantRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantRole{}
	for rows.Next() {
		var i TenantRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ParentRoleID,
			&i.Level,
			&i.IsDefault,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantRolesHierarchy = `-- name: ListTenantRolesHierarchy :many
WITH RECURSIVE role_tree AS (
    -- Base case: root roles (no parent)
    SELECT tr.id, tr.tenant_id, tr.name, tr.description, tr.parent_role_id, tr.level, tr.is_default, tr.is_active, tr.metadata, tr.created_at, tr.updated_at, 0 as depth
    FROM tenant_roles tr
    WHERE tr.parent_role_id IS NULL AND tr.tenant_id = $1 AND tr.is_active = true

    UNION ALL

    -- Recursive case: child roles
    SELECT tr.id, tr.tenant_id, tr.name, tr.description, tr.parent_role_id, tr.level, tr.is_default, tr.is_active, tr.metadata, tr.created_at, tr.updated_at, rt.depth + 1
    FROM tenant_roles tr
    JOIN role_tree rt ON tr.parent_role_id = rt.id
    WHERE tr.is_active = true AND rt.depth < 10
)
SELECT id, tenant_id, name, description, parent_role_id, level, is_default, is_active, metadata, created_at, updated_at, depth FROM role_tree
ORDER BY depth, level, name
`

type ListTenantRolesHierarchyRow struct {
	ID           int32                 `json:"id"`
	TenantID     int32                 `json:"tenant_id"`
	Name         string                `json:"name"`
	Description  sql.NullString        `json:"description"`
	ParentRoleID sql.NullInt32         `json:"parent_role_id"`
	Level        int32                 `json:"level"`
	IsDefault    sql.NullBool          `json:"is_default"`
	IsActive     sql.NullBool          `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
	Depth        int32                 `json:"depth"`
}

func (q *Queries) ListTenantRolesHierarchy(ctx context.Context, tenantID int32) ([]ListTenantRolesHierarchyRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantRolesHierarchy, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantRolesHierarchyRow{}
	for rows.Next() {
		var i ListTenantRolesHierarchyRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.ParentRoleID,
			&i.Level,
			&i.IsDefault,
			&i.IsActive,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT u.id, u.business_id, u.tenants_id, u.branch_id, u.email, u.password_hash, u.first_name, u.last_name, u.phone, u.avatar_url, u.is_active, u.last_login_at, u.email_verified, u.verification_code, u.verification_expires_at, u.metadata, u.created_at, u.updated_at, t.organization as tenant_name, b.name as business_name, br.name as branch_name
FROM users u
JOIN tenants t ON u.tenants_id = t.id
LEFT JOIN businesses b ON u.business_id = b.id
LEFT JOIN branches br ON u.branch_id = br.id
WHERE u.tenants_id = $1 AND u.is_active = true
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantUsersParams struct {
	TenantsID int32 `json:"tenants_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListTenantUsersRow struct {
	ID                    int32                 `json:"id"`
	BusinessID            sql.NullInt32         `json:"business_id"`
	TenantsID             int32                 `json:"tenants_id"`
	BranchID              sql.NullInt32         `json:"branch_id"`
	Email                 string                `json:"email"`
	PasswordHash          string                `json:"password_hash"`
	FirstName             sql.NullString        `json:"first_name"`
	LastName              sql.NullString        `json:"last_name"`
	Phone                 sql.NullString        `json:"phone"`
	AvatarUrl             sql.NullString        `json:"avatar_url"`
	IsActive              bool                  `json:"is_active"`
	LastLoginAt           sql.NullTime          `json:"last_login_at"`
	EmailVerified         sql.NullBool          `json:"email_verified"`
	VerificationCode      sql.NullString        `json:"verification_code"`
	VerificationExpiresAt sql.NullTime          `json:"verification_expires_at"`
	Metadata              pqtype.NullRawMessage `json:"metadata"`
	CreatedAt             sql.NullTime          `json:"created_at"`
	UpdatedAt             sql.NullTime          `json:"updated_at"`
	TenantName            string                `json:"tenant_name"`
	BusinessName          sql.NullString        `json:"business_name"`
	BranchName            sql.NullString        `json:"branch_name"`
}

func (q *Queries) ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]ListTenantUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantUsers, arg.TenantsID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantUsersRow{}
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.TenantsID,
			&i.BranchID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.IsActive,
			&i.LastLoginAt,
			&i.EmailVerified,
			&i.VerificationCode,
			&i.VerificationExpiresAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantName,
			&i.BusinessName,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
UPDATE user_role_assignments
SET is_active = false
WHERE user_id = $1 AND tenant_role_id = $2
AND (business_id = $3 OR ($3::integer IS NULL AND business_id IS NULL))
AND (branch_id = $4 OR ($4::integer IS NULL AND branch_id IS NULL))
`

type RemoveRoleFromUserParams struct {
	UserID       int32         `json:"user_id"`
	TenantRoleID int32         `json:"tenant_role_id"`
	BusinessID   sql.NullInt32 `json:"business_id"`
	BranchID     sql.NullInt32 `json:"branch_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, removeRoleFromUser,
		arg.UserID,
		arg.TenantRoleID,
		arg.BusinessID,
		arg.BranchID,
	)
	return err
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
UPDATE tenant_role_permissions
SET is_active = false
WHERE tenant_role_id = $1 AND permission_id = $2
AND scope_type = $3 AND (scope_id = $4 OR ($4::integer IS NULL AND scope_id IS NULL))
`

type RevokePermissionFromRoleParams struct {
	TenantRoleID int32          `json:"tenant_role_id"`
	PermissionID int32          `json:"permission_id"`
	ScopeType    sql.NullString `json:"scope_type"`
	ScopeID      sql.NullInt32  `json:"scope_id"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.ExecContext(ctx, revokePermissionFromRole,
		arg.TenantRoleID,
		arg.PermissionID,
		arg.ScopeType,
		arg.ScopeID,
	)
	return err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET description = COALESCE($1, description),
    module = COALESCE($2, module),
    action = COALESCE($3, action),
    resource = COALESCE($4, resource),
    scope = COALESCE($5, scope),
    is_active = COALESCE($6, is_active)
WHERE id = $7
RETURNING id, code, description, module, action, resource, scope, is_active, created_at
`

type UpdatePermissionParams struct {
	Description sql.NullString `json:"description"`
	Module      sql.NullString `json:"module"`
	Action      sql.NullString `json:"action"`
	Resource    sql.NullString `json:"resource"`
	Scope       sql.NullString `json:"scope"`
	IsActive    sql.NullBool   `json:"is_active"`
	ID          int32          `json:"id"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, updatePermission,
		arg.Description,
		arg.Module,
		arg.Action,
		arg.Resource,
		arg.Scope,
		arg.IsActive,
		arg.ID,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.Action,
		&i.Resource,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateTenantRole = `-- name: UpdateTenantRole :one
UPDATE tenant_roles
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    parent_role_id = COALESCE($3, parent_role_id),
    is_default = COALESCE($4, is_default),
    is_active = COALESCE($5, is_active),
    metadata = COALESCE($6, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7 AND tenant_id = $8
RETURNING id, tenant_id, name, description, parent_role_id, level, is_default, is_active, metadata, created_at, updated_at
`

type UpdateTenantRoleParams struct {
	Name         sql.NullString        `json:"name"`
	Description  sql.NullString        `json:"description"`
	ParentRoleID sql.NullInt32         `json:"parent_role_id"`
	IsDefault    sql.NullBool          `json:"is_default"`
	IsActive     sql.NullBool          `json:"is_active"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	ID           int32                 `json:"id"`
	TenantID     int32                 `json:"tenant_id"`
}

func (q *Queries) UpdateTenantRole(ctx context.Context, arg UpdateTenantRoleParams) (TenantRole, error) {
	row := q.db.QueryRowContext(ctx, updateTenantRole,
		arg.Name,
		arg.Description,
		arg.ParentRoleID,
		arg.IsDefault,
		arg.IsActive,
		arg.Metadata,
		arg.ID,
		arg.TenantID,
	)
	var i TenantRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.ParentRoleID,
		&i.Level,
		&i.IsDefault,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET first_name = COALESCE($1, first_name),
    last_name = COALESCE($2, last_name),
    email = COALESCE($3, email),
    phone = COALESCE($4, phone),
    business_id = COALESCE($5, business_id),
    branch_id = COALESCE($6, branch_id),
    avatar_url = COALESCE($7, avatar_url),
    metadata = COALESCE($8, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $9 AND tenants_id = $10
RETURNING id, business_id, tenants_id, branch_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, last_login_at, email_verified, verification_code, verification_expires_at, metadata, created_at, updated_at
`

type UpdateUserParams struct {
	FirstName  sql.NullString        `json:"first_name"`
	LastName   sql.NullString        `json:"last_name"`
	Email      sql.NullString        `json:"email"`
	Phone      sql.NullString        `json:"phone"`
	BusinessID sql.NullInt32         `json:"business_id"`
	BranchID   sql.NullInt32         `json:"branch_id"`
	AvatarUrl  sql.NullString        `json:"avatar_url"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	ID         int32                 `json:"id"`
	TenantID   int32                 `json:"tenant_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.BusinessID,
		arg.BranchID,
		arg.AvatarUrl,
		arg.Metadata,
		arg.ID,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantsID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}
