// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
    name, description, branch_id, address, phone, email,
    is_active, store_code, store_type, assigned_user, manager_id, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id
`

type CreateStoreParams struct {
	Name         string                `json:"name"`
	Description  sql.NullString        `json:"description"`
	BranchID     int32                 `json:"branch_id"`
	Address      string                `json:"address"`
	Phone        string                `json:"phone"`
	Email        string                `json:"email"`
	IsActive     sql.NullBool          `json:"is_active"`
	StoreCode    string                `json:"store_code"`
	StoreType    string                `json:"store_type"`
	AssignedUser sql.NullInt32         `json:"assigned_user"`
	ManagerID    sql.NullInt32         `json:"manager_id"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRowContext(ctx, createStore,
		arg.Name,
		arg.Description,
		arg.BranchID,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.IsActive,
		arg.StoreCode,
		arg.StoreType,
		arg.AssignedUser,
		arg.ManagerID,
		arg.Metadata,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.StoreType,
		&i.StoreCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedUser,
		&i.ManagerID,
	)
	return i, err
}

const deactivateStore = `-- name: DeactivateStore :one
UPDATE stores
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id
`

func (q *Queries) DeactivateStore(ctx context.Context, id int32) (Store, error) {
	row := q.db.QueryRowContext(ctx, deactivateStore, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.StoreType,
		&i.StoreCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedUser,
		&i.ManagerID,
	)
	return i, err
}

const deleteStore = `-- name: DeleteStore :exec
DELETE FROM stores WHERE id = $1
`

func (q *Queries) DeleteStore(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteStore, id)
	return err
}

const getCentralStoreByBranch = `-- name: GetCentralStoreByBranch :one
SELECT id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id FROM stores WHERE branch_id = $1 AND store_type = 'central' LIMIT 1
`

func (q *Queries) GetCentralStoreByBranch(ctx context.Context, branchID int32) (Store, error) {
	row := q.db.QueryRowContext(ctx, getCentralStoreByBranch, branchID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.StoreType,
		&i.StoreCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedUser,
		&i.ManagerID,
	)
	return i, err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id FROM stores WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStoreByID(ctx context.Context, id int32) (Store, error) {
	row := q.db.QueryRowContext(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.StoreType,
		&i.StoreCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedUser,
		&i.ManagerID,
	)
	return i, err
}

const getStoresByBranch = `-- name: GetStoresByBranch :many
SELECT id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id FROM stores WHERE branch_id = $1 ORDER BY name
`

func (q *Queries) GetStoresByBranch(ctx context.Context, branchID int32) ([]Store, error) {
	rows, err := q.db.QueryContext(ctx, getStoresByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BranchID,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.StoreType,
			&i.StoreCode,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedUser,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStores = `-- name: ListStores :many
SELECT id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id FROM stores ORDER BY created_at DESC
`

func (q *Queries) ListStores(ctx context.Context) ([]Store, error) {
	rows, err := q.db.QueryContext(ctx, listStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BranchID,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.StoreType,
			&i.StoreCode,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedUser,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStoresByName = `-- name: SearchStoresByName :many
SELECT id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id FROM stores
WHERE name ILIKE '%' || $1 || '%'
ORDER BY name
`

func (q *Queries) SearchStoresByName(ctx context.Context, dollar_1 sql.NullString) ([]Store, error) {
	rows, err := q.db.QueryContext(ctx, searchStoresByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BranchID,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.IsActive,
			&i.StoreType,
			&i.StoreCode,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedUser,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    address = COALESCE($4, address),
    phone = COALESCE($5, phone),
    email = COALESCE($6, email),
    is_active = COALESCE($7, is_active),
    store_code = COALESCE($8, store_code),
    store_type = COALESCE($9, store_type),
    assigned_user = COALESCE($10, assigned_user),
    manager_id = COALESCE($11, manager_id),
    metadata = COALESCE($12, metadata),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, branch_id, address, phone, email, is_active, store_type, store_code, metadata, created_at, updated_at, assigned_user, manager_id
`

type UpdateStoreParams struct {
	ID           int32                 `json:"id"`
	Name         sql.NullString        `json:"name"`
	Description  sql.NullString        `json:"description"`
	Address      sql.NullString        `json:"address"`
	Phone        sql.NullString        `json:"phone"`
	Email        sql.NullString        `json:"email"`
	IsActive     sql.NullBool          `json:"is_active"`
	StoreCode    sql.NullString        `json:"store_code"`
	StoreType    sql.NullString        `json:"store_type"`
	AssignedUser sql.NullInt32         `json:"assigned_user"`
	ManagerID    sql.NullInt32         `json:"manager_id"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRowContext(ctx, updateStore,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.IsActive,
		arg.StoreCode,
		arg.StoreType,
		arg.AssignedUser,
		arg.ManagerID,
		arg.Metadata,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BranchID,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.IsActive,
		&i.StoreType,
		&i.StoreCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssignedUser,
		&i.ManagerID,
	)
	return i, err
}
