// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supplier.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
    name, phone, email, address, metadata, business_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, phone, email, address, metadata, business_id, created_at, updated_at
`

type CreateSupplierParams struct {
	Name       string                `json:"name"`
	Phone      sql.NullString        `json:"phone"`
	Email      sql.NullString        `json:"email"`
	Address    sql.NullString        `json:"address"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	BusinessID int32                 `json:"business_id"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, createSupplier,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Metadata,
		arg.BusinessID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Metadata,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :one
DELETE FROM suppliers
WHERE id = $1 AND business_id = $2
RETURNING id, name, phone, email, address, metadata, business_id, created_at, updated_at
`

type DeleteSupplierParams struct {
	ID         int32 `json:"id"`
	BusinessID int32 `json:"business_id"`
}

func (q *Queries) DeleteSupplier(ctx context.Context, arg DeleteSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, deleteSupplier, arg.ID, arg.BusinessID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Metadata,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, phone, email, address, metadata, business_id, created_at, updated_at FROM suppliers WHERE id = $1 AND business_id = $2
`

type GetSupplierParams struct {
	ID         int32 `json:"id"`
	BusinessID int32 `json:"business_id"`
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, getSupplier, arg.ID, arg.BusinessID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Metadata,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, phone, email, address, metadata, business_id, created_at, updated_at FROM suppliers WHERE business_id = $1
ORDER BY id DESC
`

func (q *Queries) ListSuppliers(ctx context.Context, businessID int32) ([]Supplier, error) {
	rows, err := q.db.QueryContext(ctx, listSuppliers, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.Metadata,
			&i.BusinessID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET
    name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    email = COALESCE($3, email),
    address = COALESCE($4, address),
    metadata = COALESCE($5, metadata),
    updated_at = NOW()
WHERE id = $6 AND business_id = $7
RETURNING id, name, phone, email, address, metadata, business_id, created_at, updated_at
`

type UpdateSupplierParams struct {
	Name       sql.NullString        `json:"name"`
	Phone      sql.NullString        `json:"phone"`
	Email      sql.NullString        `json:"email"`
	Address    sql.NullString        `json:"address"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	ID         int32                 `json:"id"`
	BusinessID int32                 `json:"business_id"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, updateSupplier,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.Metadata,
		arg.ID,
		arg.BusinessID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Metadata,
		&i.BusinessID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
