// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id, business_id)
VALUES ($1, $2, $3)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AddPermissionToRoleParams struct {
	RoleID       int32         `json:"role_id"`
	PermissionID int32         `json:"permission_id"`
	BusinessID   sql.NullInt32 `json:"business_id"`
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionToRole, arg.RoleID, arg.PermissionID, arg.BusinessID)
	return err
}

const clearTenantResetCode = `-- name: ClearTenantResetCode :exec
UPDATE tenants
SET reset_code = NULL,
    reset_code_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearTenantResetCode(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, clearTenantResetCode, id)
	return err
}

const createActivityLog = `-- name: CreateActivityLog :one

INSERT INTO activity_logs (
    business_id, user_id, action, details, entity_id, entity_type, ip_address, user_agent, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, COALESCE($9, '{}')
)
RETURNING id, business_id, user_id, action, details, entity_id, entity_type, ip_address, user_agent, metadata, created_at
`

type CreateActivityLogParams struct {
	BusinessID int32          `json:"business_id"`
	UserID     int32          `json:"user_id"`
	Action     string         `json:"action"`
	Details    string         `json:"details"`
	EntityID   int32          `json:"entity_id"`
	EntityType string         `json:"entity_type"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	Column9    interface{}    `json:"column_9"`
}

// ACTIVITY LOGS
func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, createActivityLog,
		arg.BusinessID,
		arg.UserID,
		arg.Action,
		arg.Details,
		arg.EntityID,
		arg.EntityType,
		arg.IpAddress,
		arg.UserAgent,
		arg.Column9,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Action,
		&i.Details,
		&i.EntityID,
		&i.EntityType,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createBusinessRole = `-- name: CreateBusinessRole :one
INSERT INTO business_roles (business_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, business_id, name, description, created_at, updated_at
`

type CreateBusinessRoleParams struct {
	BusinessID  sql.NullInt32  `json:"business_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateBusinessRole(ctx context.Context, arg CreateBusinessRoleParams) (BusinessRole, error) {
	row := q.db.QueryRowContext(ctx, createBusinessRole, arg.BusinessID, arg.Name, arg.Description)
	var i BusinessRole
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLegacyPermission = `-- name: CreateLegacyPermission :one
INSERT INTO permissions (code, description)
VALUES ($1, $2)
RETURNING id, code, description, module, action, resource, scope, is_active, created_at
`

type CreateLegacyPermissionParams struct {
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

// Legacy permission creation for compatibility
func (q *Queries) CreateLegacyPermission(ctx context.Context, arg CreateLegacyPermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createLegacyPermission, arg.Code, arg.Description)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.Action,
		&i.Resource,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createLegacyUser = `-- name: CreateLegacyUser :one
INSERT INTO users(email, business_id, tenants_id, branch_id, password_hash, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, tenants_id, branch_id, email, password_hash, first_name, last_name, phone, avatar_url, is_active, last_login_at, email_verified, verification_code, verification_expires_at, metadata, created_at, updated_at
`

type CreateLegacyUserParams struct {
	Email        string        `json:"email"`
	BusinessID   sql.NullInt32 `json:"business_id"`
	TenantsID    int32         `json:"tenants_id"`
	BranchID     sql.NullInt32 `json:"branch_id"`
	PasswordHash string        `json:"password_hash"`
	IsActive     bool          `json:"is_active"`
}

// Legacy user creation for compatibility
func (q *Queries) CreateLegacyUser(ctx context.Context, arg CreateLegacyUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createLegacyUser,
		arg.Email,
		arg.BusinessID,
		arg.TenantsID,
		arg.BranchID,
		arg.PasswordHash,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TenantsID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (developer_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, developer_id, token, expires_at, used
`

type CreatePasswordResetTokenParams struct {
	DeveloperID int32     `json:"developer_id"`
	Token       string    `json:"token"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.DeveloperID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (email, password_hash, is_active, organization, plan)
VALUES ($1, $2, true, $3, $4)
RETURNING id, organization, email, password_hash, is_active, plan, email_verified, verification_code, verification_expires_at, reset_code, reset_code_expires_at, created_at, updated_at
`

type CreateTenantParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Organization string `json:"organization"`
	Plan         string `json:"plan"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.Email,
		arg.PasswordHash,
		arg.Organization,
		arg.Plan,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Organization,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.Plan,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.ResetCode,
		&i.ResetCodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActivityLog = `-- name: DeleteActivityLog :exec
DELETE FROM activity_logs
WHERE id = $1
  AND business_id = $2
`

type DeleteActivityLogParams struct {
	ID         int32 `json:"id"`
	BusinessID int32 `json:"business_id"`
}

func (q *Queries) DeleteActivityLog(ctx context.Context, arg DeleteActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityLog, arg.ID, arg.BusinessID)
	return err
}

const deleteActivityLogs = `-- name: DeleteActivityLogs :exec
DELETE FROM activity_logs
WHERE business_id = $1
  AND id = ANY($2::int[])
`

type DeleteActivityLogsParams struct {
	BusinessID int32   `json:"business_id"`
	Column2    []int32 `json:"column_2"`
}

func (q *Queries) DeleteActivityLogs(ctx context.Context, arg DeleteActivityLogsParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityLogs, arg.BusinessID, pq.Array(arg.Column2))
	return err
}

const deleteBusinessRole = `-- name: DeleteBusinessRole :exec
DELETE FROM business_roles
WHERE id = $1
`

func (q *Queries) DeleteBusinessRole(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteBusinessRole, id)
	return err
}

const getActivityLog = `-- name: GetActivityLog :one
SELECT id, business_id, user_id, action, details, entity_id, entity_type, ip_address, user_agent, metadata, created_at FROM activity_logs
WHERE id = $1
  AND business_id = $2
LIMIT 1
`

type GetActivityLogParams struct {
	ID         int32 `json:"id"`
	BusinessID int32 `json:"business_id"`
}

func (q *Queries) GetActivityLog(ctx context.Context, arg GetActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, getActivityLog, arg.ID, arg.BusinessID)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Action,
		&i.Details,
		&i.EntityID,
		&i.EntityType,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getBusinessRoleByName = `-- name: GetBusinessRoleByName :one
SELECT id, business_id, name, description, created_at, updated_at FROM business_roles
WHERE business_id = $1 AND name = $2
`

type GetBusinessRoleByNameParams struct {
	BusinessID sql.NullInt32 `json:"business_id"`
	Name       string        `json:"name"`
}

func (q *Queries) GetBusinessRoleByName(ctx context.Context, arg GetBusinessRoleByNameParams) (BusinessRole, error) {
	row := q.db.QueryRowContext(ctx, getBusinessRoleByName, arg.BusinessID, arg.Name)
	var i BusinessRole
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegacyPermissionByCode = `-- name: GetLegacyPermissionByCode :one
SELECT id, code, description, module, action, resource, scope, is_active, created_at FROM permissions
WHERE code = $1
`

func (q *Queries) GetLegacyPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getLegacyPermissionByCode, code)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Module,
		&i.Action,
		&i.Resource,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getLegacyRolePermissions = `-- name: GetLegacyRolePermissions :many
SELECT p.id, p.code, p.description, p.module, p.action, p.resource, p.scope, p.is_active, p.created_at FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.code
`

func (q *Queries) GetLegacyRolePermissions(ctx context.Context, roleID int32) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.Action,
			&i.Resource,
			&i.Scope,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginHistory = `-- name: GetLoginHistory :many
SELECT id, username_or_email, login_time, ip_address, user_agent, success, error_reason FROM login_histories
ORDER BY login_time DESC
LIMIT $1
`

func (q *Queries) GetLoginHistory(ctx context.Context, limit int32) ([]LoginHistory, error) {
	rows, err := q.db.QueryContext(ctx, getLoginHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginHistory{}
	for rows.Next() {
		var i LoginHistory
		if err := rows.Scan(
			&i.ID,
			&i.UsernameOrEmail,
			&i.LoginTime,
			&i.IpAddress,
			&i.UserAgent,
			&i.Success,
			&i.ErrorReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, developer_id, token, expires_at, used FROM password_reset_tokens
WHERE token = $1 AND expires_at > NOW() AND used = FALSE
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.DeveloperID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getTenantByEmail = `-- name: GetTenantByEmail :one
SELECT
    a.id,
    a.organization,
    a.email,
    a.password_hash,
    a.is_active,
    a.plan,
    a.email_verified,
    a.verification_code,
    a.verification_expires_at,
    a.reset_code,
    a.reset_code_expires_at
FROM tenants a
WHERE a.email = $1 LIMIT 1
`

type GetTenantByEmailRow struct {
	ID                    int32          `json:"id"`
	Organization          string         `json:"organization"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	IsActive              bool           `json:"is_active"`
	Plan                  string         `json:"plan"`
	EmailVerified         bool           `json:"email_verified"`
	VerificationCode      sql.NullString `json:"verification_code"`
	VerificationExpiresAt sql.NullTime   `json:"verification_expires_at"`
	ResetCode             sql.NullString `json:"reset_code"`
	ResetCodeExpiresAt    sql.NullTime   `json:"reset_code_expires_at"`
}

func (q *Queries) GetTenantByEmail(ctx context.Context, email string) (GetTenantByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantByEmail, email)
	var i GetTenantByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Organization,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.Plan,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.ResetCode,
		&i.ResetCodeExpiresAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, organization, email, password_hash, is_active, plan, email_verified, verification_code, verification_expires_at, reset_code, reset_code_expires_at, created_at, updated_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id int32) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Organization,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.Plan,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.ResetCode,
		&i.ResetCodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByOrganization = `-- name: GetTenantByOrganization :one
SELECT
    a.id,
    a.organization,
    a.email,
    a.password_hash,
    a.is_active,
    a.plan,
    a.email_verified,
    a.verification_code,
    a.verification_expires_at,
    a.reset_code,
    a.reset_code_expires_at
FROM tenants a
WHERE a.organization = $1 LIMIT 1
`

type GetTenantByOrganizationRow struct {
	ID                    int32          `json:"id"`
	Organization          string         `json:"organization"`
	Email                 string         `json:"email"`
	PasswordHash          string         `json:"password_hash"`
	IsActive              bool           `json:"is_active"`
	Plan                  string         `json:"plan"`
	EmailVerified         bool           `json:"email_verified"`
	VerificationCode      sql.NullString `json:"verification_code"`
	VerificationExpiresAt sql.NullTime   `json:"verification_expires_at"`
	ResetCode             sql.NullString `json:"reset_code"`
	ResetCodeExpiresAt    sql.NullTime   `json:"reset_code_expires_at"`
}

func (q *Queries) GetTenantByOrganization(ctx context.Context, organization string) (GetTenantByOrganizationRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantByOrganization, organization)
	var i GetTenantByOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Organization,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.Plan,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.ResetCode,
		&i.ResetCodeExpiresAt,
	)
	return i, err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT id, business_id, user_id, action, details, entity_id, entity_type, ip_address, user_agent, metadata, created_at FROM activity_logs
WHERE business_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListActivityLogs(ctx context.Context, businessID int32) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogs, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.EntityID,
			&i.EntityType,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityLogsByUser = `-- name: ListActivityLogsByUser :many
SELECT id, business_id, user_id, action, details, entity_id, entity_type, ip_address, user_agent, metadata, created_at FROM activity_logs
WHERE business_id = $1
  AND user_id = $2
ORDER BY created_at DESC
`

type ListActivityLogsByUserParams struct {
	BusinessID int32 `json:"business_id"`
	UserID     int32 `json:"user_id"`
}

func (q *Queries) ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogsByUser, arg.BusinessID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.EntityID,
			&i.EntityType,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessRoles = `-- name: ListBusinessRoles :many
SELECT id, business_id, name, description, created_at, updated_at FROM business_roles
WHERE business_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBusinessRoles(ctx context.Context, businessID sql.NullInt32) ([]BusinessRole, error) {
	rows, err := q.db.QueryContext(ctx, listBusinessRoles, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessRole{}
	for rows.Next() {
		var i BusinessRole
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyPermissions = `-- name: ListLegacyPermissions :many
SELECT id, code, description, module, action, resource, scope, is_active, created_at FROM permissions
ORDER BY id
`

func (q *Queries) ListLegacyPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Module,
			&i.Action,
			&i.Resource,
			&i.Scope,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logLoginAttempt = `-- name: LogLoginAttempt :exec
INSERT INTO login_histories (username_or_email, ip_address, user_agent, success, error_reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username_or_email, login_time, ip_address, user_agent, success, error_reason
`

type LogLoginAttemptParams struct {
	UsernameOrEmail string         `json:"username_or_email"`
	IpAddress       sql.NullString `json:"ip_address"`
	UserAgent       sql.NullString `json:"user_agent"`
	Success         bool           `json:"success"`
	ErrorReason     sql.NullString `json:"error_reason"`
}

func (q *Queries) LogLoginAttempt(ctx context.Context, arg LogLoginAttemptParams) error {
	_, err := q.db.ExecContext(ctx, logLoginAttempt,
		arg.UsernameOrEmail,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.ErrorReason,
	)
	return err
}

const markTenantEmailVerified = `-- name: MarkTenantEmailVerified :exec
UPDATE tenants
SET email_verified = $2,
    verification_code = NULL,
    verification_expires_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

type MarkTenantEmailVerifiedParams struct {
	ID            int32 `json:"id"`
	EmailVerified bool  `json:"email_verified"`
}

func (q *Queries) MarkTenantEmailVerified(ctx context.Context, arg MarkTenantEmailVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, markTenantEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const markTokenAsUsed = `-- name: MarkTokenAsUsed :exec
UPDATE password_reset_tokens
SET used = TRUE
WHERE id = $1
`

func (q *Queries) MarkTokenAsUsed(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markTokenAsUsed, id)
	return err
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.ExecContext(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const setTenantEmailVerification = `-- name: SetTenantEmailVerification :exec
UPDATE tenants
SET verification_code = $2,
    verification_expires_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type SetTenantEmailVerificationParams struct {
	ID                    int32          `json:"id"`
	VerificationCode      sql.NullString `json:"verification_code"`
	VerificationExpiresAt sql.NullTime   `json:"verification_expires_at"`
}

func (q *Queries) SetTenantEmailVerification(ctx context.Context, arg SetTenantEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, setTenantEmailVerification, arg.ID, arg.VerificationCode, arg.VerificationExpiresAt)
	return err
}

const setTenantResetCode = `-- name: SetTenantResetCode :exec
UPDATE tenants
SET reset_code = $2,
    reset_code_expires_at = $3,
    updated_at = NOW()
WHERE id = $1
`

type SetTenantResetCodeParams struct {
	ID                 int32          `json:"id"`
	ResetCode          sql.NullString `json:"reset_code"`
	ResetCodeExpiresAt sql.NullTime   `json:"reset_code_expires_at"`
}

func (q *Queries) SetTenantResetCode(ctx context.Context, arg SetTenantResetCodeParams) error {
	_, err := q.db.ExecContext(ctx, setTenantResetCode, arg.ID, arg.ResetCode, arg.ResetCodeExpiresAt)
	return err
}

const updateBusinessRole = `-- name: UpdateBusinessRole :one
UPDATE business_roles
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, business_id, name, description, created_at, updated_at
`

type UpdateBusinessRoleParams struct {
	ID          int32          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateBusinessRole(ctx context.Context, arg UpdateBusinessRoleParams) (BusinessRole, error) {
	row := q.db.QueryRowContext(ctx, updateBusinessRole, arg.ID, arg.Name, arg.Description)
	var i BusinessRole
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET organization   = COALESCE($1, organization),
    email      = COALESCE($2, email),
    is_active  = COALESCE($3, is_active)
WHERE id = $4
RETURNING id, organization, email, password_hash, is_active, plan, email_verified, verification_code, verification_expires_at, reset_code, reset_code_expires_at, created_at, updated_at
`

type UpdateTenantParams struct {
	Organization sql.NullString `json:"organization"`
	Email        sql.NullString `json:"email"`
	IsActive     sql.NullBool   `json:"is_active"`
	ID           int32          `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenant,
		arg.Organization,
		arg.Email,
		arg.IsActive,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Organization,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.Plan,
		&i.EmailVerified,
		&i.VerificationCode,
		&i.VerificationExpiresAt,
		&i.ResetCode,
		&i.ResetCodeExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantPassword = `-- name: UpdateTenantPassword :exec
UPDATE tenants
SET password_hash = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTenantPasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateTenantPassword(ctx context.Context, arg UpdateTenantPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants
SET is_active = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTenantStatusParams struct {
	ID       int32 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantStatus, arg.ID, arg.IsActive)
	return err
}
