// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (name, description, url, secret, events, tenant_id, max_retries, timeout_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, url, secret, events, tenant_id, is_active, retry_count, max_retries, timeout_ms, created_at, updated_at
`

type CreateWebhookParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	Secret      string         `json:"secret"`
	Events      []string       `json:"events"`
	TenantID    int32          `json:"tenant_id"`
	MaxRetries  sql.NullInt32  `json:"max_retries"`
	TimeoutMs   sql.NullInt32  `json:"timeout_ms"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Secret,
		pq.Array(arg.Events),
		arg.TenantID,
		arg.MaxRetries,
		arg.TimeoutMs,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Secret,
		pq.Array(&i.Events),
		&i.TenantID,
		&i.IsActive,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1 AND tenant_id = $2
`

type DeleteWebhookParams struct {
	ID       int32 `json:"id"`
	TenantID int32 `json:"tenant_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, arg.ID, arg.TenantID)
	return err
}

const getDeliveryStats = `-- name: GetDeliveryStats :one
SELECT
    COUNT(*) as total_deliveries,
    COUNT(CASE WHEN response_status BETWEEN 200 AND 299 THEN 1 END) as successful_deliveries,
    COUNT(CASE WHEN response_status IS NULL OR response_status NOT BETWEEN 200 AND 299 THEN 1 END) as failed_deliveries,
    AVG(EXTRACT(EPOCH FROM (delivered_at - created_at))) as avg_delivery_time_seconds
FROM webhook_deliveries
WHERE webhook_id = $1 AND created_at >= $2 AND created_at <= $3
`

type GetDeliveryStatsParams struct {
	WebhookID   int32        `json:"webhook_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	CreatedAt_2 sql.NullTime `json:"created_at_2"`
}

type GetDeliveryStatsRow struct {
	TotalDeliveries        int64   `json:"total_deliveries"`
	SuccessfulDeliveries   int64   `json:"successful_deliveries"`
	FailedDeliveries       int64   `json:"failed_deliveries"`
	AvgDeliveryTimeSeconds float64 `json:"avg_delivery_time_seconds"`
}

func (q *Queries) GetDeliveryStats(ctx context.Context, arg GetDeliveryStatsParams) (GetDeliveryStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryStats, arg.WebhookID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetDeliveryStatsRow
	err := row.Scan(
		&i.TotalDeliveries,
		&i.SuccessfulDeliveries,
		&i.FailedDeliveries,
		&i.AvgDeliveryTimeSeconds,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, name, description, url, secret, events, tenant_id, is_active, retry_count, max_retries, timeout_ms, created_at, updated_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id int32) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Secret,
		pq.Array(&i.Events),
		&i.TenantID,
		&i.IsActive,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDeliveries = `-- name: GetWebhookDeliveries :many
SELECT wd.id, wd.webhook_id, wd.event_type, wd.payload, wd.response_status, wd.response_body, wd.error_message, wd.attempt_number, wd.delivered_at, wd.created_at, w.name as webhook_name, w.url as webhook_url
FROM webhook_deliveries wd
JOIN webhooks w ON wd.webhook_id = w.id
WHERE wd.webhook_id = $1
ORDER BY wd.created_at DESC
LIMIT $2
`

type GetWebhookDeliveriesParams struct {
	WebhookID int32 `json:"webhook_id"`
	Limit     int32 `json:"limit"`
}

type GetWebhookDeliveriesRow struct {
	ID             int32           `json:"id"`
	WebhookID      int32           `json:"webhook_id"`
	EventType      string          `json:"event_type"`
	Payload        json.RawMessage `json:"payload"`
	ResponseStatus sql.NullInt32   `json:"response_status"`
	ResponseBody   sql.NullString  `json:"response_body"`
	ErrorMessage   sql.NullString  `json:"error_message"`
	AttemptNumber  sql.NullInt32   `json:"attempt_number"`
	DeliveredAt    sql.NullTime    `json:"delivered_at"`
	CreatedAt      sql.NullTime    `json:"created_at"`
	WebhookName    string          `json:"webhook_name"`
	WebhookUrl     string          `json:"webhook_url"`
}

func (q *Queries) GetWebhookDeliveries(ctx context.Context, arg GetWebhookDeliveriesParams) ([]GetWebhookDeliveriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getWebhookDeliveries, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWebhookDeliveriesRow{}
	for rows.Next() {
		var i GetWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.EventType,
			&i.Payload,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.ErrorMessage,
			&i.AttemptNumber,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.WebhookName,
			&i.WebhookUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookEvents = `-- name: GetWebhookEvents :many
SELECT id, event_type, description, module, created_at FROM webhook_events ORDER BY module, event_type
`

func (q *Queries) GetWebhookEvents(ctx context.Context) ([]WebhookEvent, error) {
	rows, err := q.db.QueryContext(ctx, getWebhookEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Description,
			&i.Module,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhooksByEvent = `-- name: GetWebhooksByEvent :many
SELECT id, name, description, url, secret, events, tenant_id, is_active, retry_count, max_retries, timeout_ms, created_at, updated_at FROM webhooks
WHERE tenant_id = $1 AND $2 = ANY(events) AND is_active = true
ORDER BY created_at DESC
`

type GetWebhooksByEventParams struct {
	TenantID int32    `json:"tenant_id"`
	Events   []string `json:"events"`
}

func (q *Queries) GetWebhooksByEvent(ctx context.Context, arg GetWebhooksByEventParams) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, getWebhooksByEvent, arg.TenantID, pq.Array(arg.Events))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.Secret,
			pq.Array(&i.Events),
			&i.TenantID,
			&i.IsActive,
			&i.RetryCount,
			&i.MaxRetries,
			&i.TimeoutMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhooksByUser = `-- name: GetWebhooksByUser :many
SELECT id, name, description, url, secret, events, tenant_id, is_active, retry_count, max_retries, timeout_ms, created_at, updated_at FROM webhooks WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetWebhooksByUser(ctx context.Context, tenantID int32) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, getWebhooksByUser, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.Secret,
			pq.Array(&i.Events),
			&i.TenantID,
			&i.IsActive,
			&i.RetryCount,
			&i.MaxRetries,
			&i.TimeoutMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event_type, payload, attempt_number)
VALUES ($1, $2, $3, $4)
RETURNING id, webhook_id, event_type, payload, response_status, response_body, error_message, attempt_number, delivered_at, created_at
`

type RecordWebhookDeliveryParams struct {
	WebhookID     int32           `json:"webhook_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	AttemptNumber sql.NullInt32   `json:"attempt_number"`
}

func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRowContext(ctx, recordWebhookDelivery,
		arg.WebhookID,
		arg.EventType,
		arg.Payload,
		arg.AttemptNumber,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.EventType,
		&i.Payload,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ErrorMessage,
		&i.AttemptNumber,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET name = $2, description = $3, url = $4, events = $5, is_active = $6,
    max_retries = $7, timeout_ms = $8, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND tenant_id = $2
RETURNING id, name, description, url, secret, events, tenant_id, is_active, retry_count, max_retries, timeout_ms, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Url         string         `json:"url"`
	Events      []string       `json:"events"`
	IsActive    sql.NullBool   `json:"is_active"`
	MaxRetries  sql.NullInt32  `json:"max_retries"`
	TimeoutMs   sql.NullInt32  `json:"timeout_ms"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Url,
		pq.Array(arg.Events),
		arg.IsActive,
		arg.MaxRetries,
		arg.TimeoutMs,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Secret,
		pq.Array(&i.Events),
		&i.TenantID,
		&i.IsActive,
		&i.RetryCount,
		&i.MaxRetries,
		&i.TimeoutMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :exec
UPDATE webhook_deliveries
SET response_status = $2, response_body = $3, error_message = $4, delivered_at = $5
WHERE id = $1
`

type UpdateWebhookDeliveryParams struct {
	ID             int32          `json:"id"`
	ResponseStatus sql.NullInt32  `json:"response_status"`
	ResponseBody   sql.NullString `json:"response_body"`
	ErrorMessage   sql.NullString `json:"error_message"`
	DeliveredAt    sql.NullTime   `json:"delivered_at"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookDelivery,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ErrorMessage,
		arg.DeliveredAt,
	)
	return err
}
